// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package enrollmentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelEnrollment = `-- name: CancelEnrollment :execrows
UPDATE enrollments
SET status = 'cancelled', updated_at = now(), updated_by = $2
WHERE id = $1 AND status IN ('pending', 'paid') AND deleted_at IS NULL
`

type CancelEnrollmentParams struct {
	ID        pgtype.UUID
	UpdatedBy pgtype.UUID
}

func (q *Queries) CancelEnrollment(ctx context.Context, arg CancelEnrollmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelEnrollment, arg.ID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveEnrollments = `-- name: CountActiveEnrollments :one
SELECT count(*) FROM enrollments
WHERE program_id = $1 AND year = $2
  AND status <> 'cancelled' AND deleted_at IS NULL
`

type CountActiveEnrollmentsParams struct {
	ProgramID pgtype.UUID
	Year      int32
}

func (q *Queries) CountActiveEnrollments(ctx context.Context, arg CountActiveEnrollmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveEnrollments, arg.ProgramID, arg.Year)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getEnrollment = `-- name: GetEnrollment :one
SELECT id, student_id, program_id, year, status, paid_at, created_at, updated_at, deleted_at, created_by, updated_by FROM enrollments WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetEnrollment(ctx context.Context, id pgtype.UUID) (Enrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollment, id)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ProgramID,
		&i.Year,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getEnrollmentByKeyForUpdate = `-- name: GetEnrollmentByKeyForUpdate :one
SELECT id, student_id, program_id, year, status, paid_at, created_at, updated_at, deleted_at, created_by, updated_by FROM enrollments
WHERE student_id = $1 AND program_id = $2 AND year = $3
FOR UPDATE
`

type GetEnrollmentByKeyForUpdateParams struct {
	StudentID pgtype.UUID
	ProgramID pgtype.UUID
	Year      int32
}

func (q *Queries) GetEnrollmentByKeyForUpdate(ctx context.Context, arg GetEnrollmentByKeyForUpdateParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollmentByKeyForUpdate, arg.StudentID, arg.ProgramID, arg.Year)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ProgramID,
		&i.Year,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const insertEnrollment = `-- name: InsertEnrollment :one
INSERT INTO enrollments (student_id, program_id, year, status, created_by, updated_by)
VALUES ($1, $2, $3, 'pending', $4, $5)
RETURNING id, student_id, program_id, year, status, paid_at, created_at, updated_at, deleted_at, created_by, updated_by
`

type InsertEnrollmentParams struct {
	StudentID pgtype.UUID
	ProgramID pgtype.UUID
	Year      int32
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
}

func (q *Queries) InsertEnrollment(ctx context.Context, arg InsertEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, insertEnrollment,
		arg.StudentID,
		arg.ProgramID,
		arg.Year,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ProgramID,
		&i.Year,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listEnrollments = `-- name: ListEnrollments :many
SELECT id, student_id, program_id, year, status, paid_at, created_at, updated_at, deleted_at, created_by, updated_by FROM enrollments
WHERE deleted_at IS NULL
  AND ($1::uuid IS NULL OR id < $1::uuid)
  AND ($2::uuid IS NULL OR student_id = $2::uuid)
  AND ($3::uuid IS NULL OR program_id = $3::uuid)
  AND ($4::int IS NULL OR year = $4::int)
  AND ($5::text IS NULL OR status = $5::text)
ORDER BY id DESC
LIMIT $6::int
`

type ListEnrollmentsParams struct {
	PageToken pgtype.UUID
	StudentID pgtype.UUID
	ProgramID pgtype.UUID
	Year      pgtype.Int4
	Status    pgtype.Text
	RowLimit  int32
}

func (q *Queries) ListEnrollments(ctx context.Context, arg ListEnrollmentsParams) ([]Enrollment, error) {
	rows, err := q.db.Query(ctx, listEnrollments,
		arg.PageToken,
		arg.StudentID,
		arg.ProgramID,
		arg.Year,
		arg.Status,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Enrollment
	for rows.Next() {
		var i Enrollment
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.ProgramID,
			&i.Year,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnEnrollments = `-- name: ListOwnEnrollments :many
SELECT id, student_id, program_id, year, status, paid_at, created_at, updated_at, deleted_at, created_by, updated_by FROM enrollments
WHERE student_id = $1::uuid AND deleted_at IS NULL
  AND ($2::uuid IS NULL OR id < $2::uuid)
ORDER BY id DESC
LIMIT $3::int
`

type ListOwnEnrollmentsParams struct {
	StudentID pgtype.UUID
	PageToken pgtype.UUID
	RowLimit  int32
}

func (q *Queries) ListOwnEnrollments(ctx context.Context, arg ListOwnEnrollmentsParams) ([]Enrollment, error) {
	rows, err := q.db.Query(ctx, listOwnEnrollments, arg.StudentID, arg.PageToken, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Enrollment
	for rows.Next() {
		var i Enrollment
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.ProgramID,
			&i.Year,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProgramQuotaForYear = `-- name: LockProgramQuotaForYear :one
SELECT capacity FROM program_quotas
WHERE program_id = $1 AND year = $2 AND deleted_at IS NULL
FOR UPDATE
`

type LockProgramQuotaForYearParams struct {
	ProgramID pgtype.UUID
	Year      int32
}

func (q *Queries) LockProgramQuotaForYear(ctx context.Context, arg LockProgramQuotaForYearParams) (int32, error) {
	row := q.db.QueryRow(ctx, lockProgramQuotaForYear, arg.ProgramID, arg.Year)
	var capacity int32
	err := row.Scan(&capacity)
	return capacity, err
}

const markEnrollmentPaid = `-- name: MarkEnrollmentPaid :one
UPDATE enrollments
SET status = 'paid', paid_at = now(), updated_at = now(), updated_by = $2
WHERE id = $1 AND status = 'pending' AND deleted_at IS NULL
RETURNING id, student_id, program_id, year, status, paid_at, created_at, updated_at, deleted_at, created_by, updated_by
`

type MarkEnrollmentPaidParams struct {
	ID        pgtype.UUID
	UpdatedBy pgtype.UUID
}

func (q *Queries) MarkEnrollmentPaid(ctx context.Context, arg MarkEnrollmentPaidParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, markEnrollmentPaid, arg.ID, arg.UpdatedBy)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ProgramID,
		&i.Year,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const reviveEnrollment = `-- name: ReviveEnrollment :one
UPDATE enrollments
SET status = 'pending', paid_at = NULL, deleted_at = NULL,
    updated_at = now(), updated_by = $2
WHERE id = $1
RETURNING id, student_id, program_id, year, status, paid_at, created_at, updated_at, deleted_at, created_by, updated_by
`

type ReviveEnrollmentParams struct {
	ID        pgtype.UUID
	UpdatedBy pgtype.UUID
}

func (q *Queries) ReviveEnrollment(ctx context.Context, arg ReviveEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, reviveEnrollment, arg.ID, arg.UpdatedBy)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ProgramID,
		&i.Year,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
