// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package enrollmentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelEnrollment(ctx context.Context, arg CancelEnrollmentParams) (int64, error)
	CountActiveEnrollments(ctx context.Context, arg CountActiveEnrollmentsParams) (int64, error)
	GetEnrollment(ctx context.Context, id pgtype.UUID) (Enrollment, error)
	GetEnrollmentByKeyForUpdate(ctx context.Context, arg GetEnrollmentByKeyForUpdateParams) (Enrollment, error)
	InsertEnrollment(ctx context.Context, arg InsertEnrollmentParams) (Enrollment, error)
	ListEnrollments(ctx context.Context, arg ListEnrollmentsParams) ([]Enrollment, error)
	ListOwnEnrollments(ctx context.Context, studentID pgtype.UUID) ([]Enrollment, error)
	LockProgramQuotaForYear(ctx context.Context, arg LockProgramQuotaForYearParams) (int32, error)
	MarkEnrollmentPaid(ctx context.Context, arg MarkEnrollmentPaidParams) (Enrollment, error)
	ReviveEnrollment(ctx context.Context, arg ReviveEnrollmentParams) (Enrollment, error)
}

var _ Querier = (*Queries)(nil)
