// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package enrollmentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelEnrollment = `-- name: CancelEnrollment :execrows
UPDATE enrollments
SET status = 'cancelled', updated_at = now(), updated_by = $2
WHERE id = $1 AND status IN ('pending', 'paid') AND deleted_at IS NULL
`

type CancelEnrollmentParams struct {
	ID        pgtype.UUID
	UpdatedBy pgtype.UUID
}

func (q *Queries) CancelEnrollment(ctx context.Context, arg CancelEnrollmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelEnrollment, arg.ID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveEnrollments = `-- name: CountActiveEnrollments :one
SELECT count(*) FROM enrollments
WHERE program_id = $1 AND year = $2
  AND status <> 'cancelled' AND deleted_at IS NULL
`

type CountActiveEnrollmentsParams struct {
	ProgramID pgtype.UUID
	Year      int32
}

func (q *Queries) CountActiveEnrollments(ctx context.Context, arg CountActiveEnrollmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveEnrollments, arg.ProgramID, arg.Year)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getEnrollment = `-- name: GetEnrollment :one
SELECT id, student_id, program_id, year, status, paid_at, created_at, updated_at, deleted_at, created_by, updated_by FROM enrollments WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetEnrollment(ctx context.Context, id pgtype.UUID) (Enrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollment, id)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ProgramID,
		&i.Year,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getEnrollmentByKeyForUpdate = `-- name: GetEnrollmentByKeyForUpdate :one
SELECT id, student_id, program_id, year, status, paid_at, created_at, updated_at, deleted_at, created_by, updated_by FROM enrollments
WHERE student_id = $1 AND program_id = $2 AND year = $3
FOR UPDATE
`

type GetEnrollmentByKeyForUpdateParams struct {
	StudentID pgtype.UUID
	ProgramID pgtype.UUID
	Year      int32
}

func (q *Queries) GetEnrollmentByKeyForUpdate(ctx context.Context, arg GetEnrollmentByKeyForUpdateParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollmentByKeyForUpdate, arg.StudentID, arg.ProgramID, arg.Year)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ProgramID,
		&i.Year,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const insertEnrollment = `-- name: InsertEnrollment :one
INSERT INTO enrollments (student_id, program_id, year, status, created_by, updated_by)
VALUES ($1, $2, $3, 'pending', $4, $5)
RETURNING id, student_id, program_id, year, status, paid_at, created_at, updated_at, deleted_at, created_by, updated_by
`

type InsertEnrollmentParams struct {
	StudentID pgtype.UUID
	ProgramID pgtype.UUID
	Year      int32
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
}

func (q *Queries) InsertEnrollment(ctx context.Context, arg InsertEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, insertEnrollment,
		arg.StudentID,
		arg.ProgramID,
		arg.Year,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ProgramID,
		&i.Year,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listEnrollments = `-- name: ListEnrollments :many
SELECT
  e.id, e.student_id, e.program_id, e.year, e.status, e.paid_at,
  e.created_at, e.updated_at, e.deleted_at, e.created_by, e.updated_by,
  COALESCE(NULLIF(TRIM(COALESCE(p.given_names,'')||' '||COALESCE(p.last_name_paternal,'')), ''), u.email, '') AS student_name,
  COALESCE(pr.name, '') AS program_name
FROM enrollments e
LEFT JOIN users u ON u.id = e.student_id AND u.deleted_at IS NULL
LEFT JOIN user_profiles p ON p.user_id = e.student_id AND p.deleted_at IS NULL
LEFT JOIN programs pr ON pr.id = e.program_id AND pr.deleted_at IS NULL
WHERE e.deleted_at IS NULL
  AND ($1::uuid IS NULL OR e.id < $1::uuid)
  AND ($2::uuid IS NULL OR e.student_id = $2::uuid)
  AND ($3::uuid IS NULL OR e.program_id = $3::uuid)
  AND ($4::int IS NULL OR e.year = $4::int)
  AND ($5::text IS NULL OR e.status = $5::text)
  AND ($6::text IS NULL
       OR u.email ILIKE '%' || $6 || '%' ESCAPE '\'
       OR (COALESCE(p.given_names,'')||' '||COALESCE(p.last_name_paternal,'')) ILIKE '%' || $6 || '%' ESCAPE '\'
       OR pr.code ILIKE '%' || $6 || '%' ESCAPE '\'
       OR pr.name ILIKE '%' || $6 || '%' ESCAPE '\')
ORDER BY e.id DESC
LIMIT $7::int
`

type ListEnrollmentsParams struct {
	PageToken pgtype.UUID
	StudentID pgtype.UUID
	ProgramID pgtype.UUID
	Year      pgtype.Int4
	Status    pgtype.Text
	Query     pgtype.Text
	RowLimit  int32
}

type ListEnrollmentsRow struct {
	ID          pgtype.UUID
	StudentID   pgtype.UUID
	ProgramID   pgtype.UUID
	Year        int32
	Status      string
	PaidAt      pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	UpdatedBy   pgtype.UUID
	StudentName string
	ProgramName string
}

func (q *Queries) ListEnrollments(ctx context.Context, arg ListEnrollmentsParams) ([]ListEnrollmentsRow, error) {
	rows, err := q.db.Query(ctx, listEnrollments,
		arg.PageToken,
		arg.StudentID,
		arg.ProgramID,
		arg.Year,
		arg.Status,
		arg.Query,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnrollmentsRow
	for rows.Next() {
		var i ListEnrollmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.ProgramID,
			&i.Year,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.StudentName,
			&i.ProgramName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnEnrollments = `-- name: ListOwnEnrollments :many
SELECT
  e.id,
  e.student_id,
  e.program_id,
  e.year,
  e.status,
  e.paid_at,
  e.created_at,
  e.updated_at,
  e.deleted_at,
  e.created_by,
  e.updated_by,
  p.name AS program_name
FROM enrollments e
JOIN programs p ON p.id = e.program_id
WHERE e.student_id = $1::uuid AND e.deleted_at IS NULL
  AND ($2::uuid IS NULL OR e.id < $2::uuid)
ORDER BY e.id DESC
LIMIT $3::int
`

type ListOwnEnrollmentsParams struct {
	StudentID pgtype.UUID
	PageToken pgtype.UUID
	RowLimit  int32
}

type ListOwnEnrollmentsRow struct {
	ID          pgtype.UUID
	StudentID   pgtype.UUID
	ProgramID   pgtype.UUID
	Year        int32
	Status      string
	PaidAt      pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	UpdatedBy   pgtype.UUID
	ProgramName string
}

func (q *Queries) ListOwnEnrollments(ctx context.Context, arg ListOwnEnrollmentsParams) ([]ListOwnEnrollmentsRow, error) {
	rows, err := q.db.Query(ctx, listOwnEnrollments, arg.StudentID, arg.PageToken, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnEnrollmentsRow
	for rows.Next() {
		var i ListOwnEnrollmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.ProgramID,
			&i.Year,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.ProgramName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProgramQuotaForYear = `-- name: LockProgramQuotaForYear :one
SELECT capacity FROM program_quotas
WHERE program_id = $1 AND year = $2 AND deleted_at IS NULL
FOR UPDATE
`

type LockProgramQuotaForYearParams struct {
	ProgramID pgtype.UUID
	Year      int32
}

func (q *Queries) LockProgramQuotaForYear(ctx context.Context, arg LockProgramQuotaForYearParams) (int32, error) {
	row := q.db.QueryRow(ctx, lockProgramQuotaForYear, arg.ProgramID, arg.Year)
	var capacity int32
	err := row.Scan(&capacity)
	return capacity, err
}

const markEnrollmentPaid = `-- name: MarkEnrollmentPaid :one
UPDATE enrollments
SET status = 'paid', paid_at = now(), updated_at = now(), updated_by = $2
WHERE id = $1 AND status = 'pending' AND deleted_at IS NULL
RETURNING id, student_id, program_id, year, status, paid_at, created_at, updated_at, deleted_at, created_by, updated_by
`

type MarkEnrollmentPaidParams struct {
	ID        pgtype.UUID
	UpdatedBy pgtype.UUID
}

func (q *Queries) MarkEnrollmentPaid(ctx context.Context, arg MarkEnrollmentPaidParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, markEnrollmentPaid, arg.ID, arg.UpdatedBy)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ProgramID,
		&i.Year,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const markOwnEnrollmentPaid = `-- name: MarkOwnEnrollmentPaid :one
UPDATE enrollments
SET status = 'paid', paid_at = now(), updated_at = now(), updated_by = $3
WHERE id = $1 AND student_id = $2 AND status = 'pending' AND deleted_at IS NULL
RETURNING id, student_id, program_id, year, status, paid_at, created_at, updated_at, deleted_at, created_by, updated_by
`

type MarkOwnEnrollmentPaidParams struct {
	ID        pgtype.UUID
	StudentID pgtype.UUID
	UpdatedBy pgtype.UUID
}

// Transitions pending → paid only when id AND student_id match, preventing cross-student writes.
func (q *Queries) MarkOwnEnrollmentPaid(ctx context.Context, arg MarkOwnEnrollmentPaidParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, markOwnEnrollmentPaid, arg.ID, arg.StudentID, arg.UpdatedBy)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ProgramID,
		&i.Year,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const reviveEnrollment = `-- name: ReviveEnrollment :one
UPDATE enrollments
SET status = 'pending', paid_at = NULL, deleted_at = NULL,
    updated_at = now(), updated_by = $2
WHERE id = $1
RETURNING id, student_id, program_id, year, status, paid_at, created_at, updated_at, deleted_at, created_by, updated_by
`

type ReviveEnrollmentParams struct {
	ID        pgtype.UUID
	UpdatedBy pgtype.UUID
}

func (q *Queries) ReviveEnrollment(ctx context.Context, arg ReviveEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, reviveEnrollment, arg.ID, arg.UpdatedBy)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ProgramID,
		&i.Year,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
