// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package catalogdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountCourseProgramAssociations(ctx context.Context, courseID pgtype.UUID) (int64, error)
	CountLiveProgramQuotas(ctx context.Context, programID pgtype.UUID) (int64, error)
	CountLiveSectionsByAcademicPeriod(ctx context.Context, academicPeriodID pgtype.UUID) (int64, error)
	CountLiveSectionsByCourse(ctx context.Context, courseID pgtype.UUID) (int64, error)
	CountProgramCourses(ctx context.Context, programID pgtype.UUID) (int64, error)
	CountSectionTeachers(ctx context.Context, sectionID pgtype.UUID) (int64, error)
	DeleteProgramCourse(ctx context.Context, arg DeleteProgramCourseParams) (int64, error)
	DeleteSectionTeacher(ctx context.Context, arg DeleteSectionTeacherParams) (int64, error)
	GetAcademicPeriod(ctx context.Context, id pgtype.UUID) (AcademicPeriod, error)
	GetCourse(ctx context.Context, id pgtype.UUID) (Course, error)
	GetProgram(ctx context.Context, id pgtype.UUID) (Program, error)
	GetProgramQuota(ctx context.Context, id pgtype.UUID) (ProgramQuota, error)
	GetSection(ctx context.Context, id pgtype.UUID) (Section, error)
	// Academic periods
	InsertAcademicPeriod(ctx context.Context, arg InsertAcademicPeriodParams) (AcademicPeriod, error)
	// Courses
	InsertCourse(ctx context.Context, arg InsertCourseParams) (Course, error)
	// Programs
	InsertProgram(ctx context.Context, arg InsertProgramParams) (Program, error)
	// Program courses (M:N append-only)
	InsertProgramCourse(ctx context.Context, arg InsertProgramCourseParams) (ProgramCourse, error)
	// Sections
	InsertSection(ctx context.Context, arg InsertSectionParams) (Section, error)
	// Section teachers (M:N append-only)
	InsertSectionTeacher(ctx context.Context, arg InsertSectionTeacherParams) (SectionTeacher, error)
	ListAcademicPeriods(ctx context.Context) ([]AcademicPeriod, error)
	ListCourses(ctx context.Context) ([]Course, error)
	ListProgramCourses(ctx context.Context, programID pgtype.UUID) ([]ProgramCourse, error)
	ListProgramQuotas(ctx context.Context, programID pgtype.UUID) ([]ProgramQuota, error)
	ListPrograms(ctx context.Context) ([]Program, error)
	ListSectionTeachers(ctx context.Context, sectionID pgtype.UUID) ([]SectionTeacher, error)
	ListSections(ctx context.Context) ([]Section, error)
	SoftDeleteAcademicPeriod(ctx context.Context, id pgtype.UUID) (int64, error)
	SoftDeleteCourse(ctx context.Context, id pgtype.UUID) (int64, error)
	SoftDeleteProgram(ctx context.Context, id pgtype.UUID) (int64, error)
	SoftDeleteProgramQuota(ctx context.Context, arg SoftDeleteProgramQuotaParams) (int64, error)
	SoftDeleteSection(ctx context.Context, arg SoftDeleteSectionParams) (int64, error)
	UpdateAcademicPeriod(ctx context.Context, arg UpdateAcademicPeriodParams) (AcademicPeriod, error)
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error)
	UpdateProgram(ctx context.Context, arg UpdateProgramParams) (Program, error)
	UpdateProgramQuota(ctx context.Context, arg UpdateProgramQuotaParams) (ProgramQuota, error)
	UpdateSection(ctx context.Context, arg UpdateSectionParams) (Section, error)
	// Program quotas
	UpsertProgramQuota(ctx context.Context, arg UpsertProgramQuotaParams) (ProgramQuota, error)
}

var _ Querier = (*Queries)(nil)
