// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package catalogdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountLiveProgramQuotas(ctx context.Context, programID pgtype.UUID) (int64, error)
	CountProgramCourses(ctx context.Context, programID pgtype.UUID) (int64, error)
	DeleteProgramCourse(ctx context.Context, arg DeleteProgramCourseParams) error
	GetAcademicPeriod(ctx context.Context, id pgtype.UUID) (AcademicPeriod, error)
	GetCourse(ctx context.Context, id pgtype.UUID) (Course, error)
	GetProgram(ctx context.Context, id pgtype.UUID) (Program, error)
	GetProgramQuota(ctx context.Context, id pgtype.UUID) (ProgramQuota, error)
	// Academic periods
	InsertAcademicPeriod(ctx context.Context, arg InsertAcademicPeriodParams) (AcademicPeriod, error)
	// Courses
	InsertCourse(ctx context.Context, arg InsertCourseParams) (Course, error)
	// Programs
	InsertProgram(ctx context.Context, arg InsertProgramParams) (Program, error)
	// Program courses (M:N append-only)
	InsertProgramCourse(ctx context.Context, arg InsertProgramCourseParams) (ProgramCourse, error)
	// Program quotas
	InsertProgramQuota(ctx context.Context, arg InsertProgramQuotaParams) (ProgramQuota, error)
	ListAcademicPeriods(ctx context.Context) ([]AcademicPeriod, error)
	ListCourses(ctx context.Context) ([]Course, error)
	ListProgramCourses(ctx context.Context, programID pgtype.UUID) ([]ProgramCourse, error)
	ListProgramQuotas(ctx context.Context, programID pgtype.UUID) ([]ProgramQuota, error)
	ListPrograms(ctx context.Context) ([]Program, error)
	SoftDeleteAcademicPeriod(ctx context.Context, id pgtype.UUID) error
	SoftDeleteCourse(ctx context.Context, id pgtype.UUID) error
	SoftDeleteProgram(ctx context.Context, id pgtype.UUID) error
	SoftDeleteProgramQuota(ctx context.Context, arg SoftDeleteProgramQuotaParams) error
	UpdateAcademicPeriod(ctx context.Context, arg UpdateAcademicPeriodParams) (AcademicPeriod, error)
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error)
	UpdateProgram(ctx context.Context, arg UpdateProgramParams) (Program, error)
	UpdateProgramQuota(ctx context.Context, arg UpdateProgramQuotaParams) (ProgramQuota, error)
}

var _ Querier = (*Queries)(nil)
