// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package catalogdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCourseProgramAssociations = `-- name: CountCourseProgramAssociations :one
SELECT count(*) FROM program_courses
WHERE course_id = $1
`

func (q *Queries) CountCourseProgramAssociations(ctx context.Context, courseID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCourseProgramAssociations, courseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLiveProgramQuotas = `-- name: CountLiveProgramQuotas :one
SELECT count(*) FROM program_quotas
WHERE program_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountLiveProgramQuotas(ctx context.Context, programID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveProgramQuotas, programID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLiveSectionsByAcademicPeriod = `-- name: CountLiveSectionsByAcademicPeriod :one
SELECT count(*) FROM sections
WHERE academic_period_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountLiveSectionsByAcademicPeriod(ctx context.Context, academicPeriodID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveSectionsByAcademicPeriod, academicPeriodID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLiveSectionsByCourse = `-- name: CountLiveSectionsByCourse :one
SELECT count(*) FROM sections
WHERE course_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountLiveSectionsByCourse(ctx context.Context, courseID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveSectionsByCourse, courseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProgramCourses = `-- name: CountProgramCourses :one
SELECT count(*) FROM program_courses
WHERE program_id = $1
`

func (q *Queries) CountProgramCourses(ctx context.Context, programID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProgramCourses, programID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSectionTeachers = `-- name: CountSectionTeachers :one
SELECT count(*) FROM section_teachers
WHERE section_id = $1
`

func (q *Queries) CountSectionTeachers(ctx context.Context, sectionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSectionTeachers, sectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProgramCourse = `-- name: DeleteProgramCourse :execrows
DELETE FROM program_courses
WHERE program_id = $1 AND course_id = $2
`

type DeleteProgramCourseParams struct {
	ProgramID pgtype.UUID
	CourseID  pgtype.UUID
}

func (q *Queries) DeleteProgramCourse(ctx context.Context, arg DeleteProgramCourseParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProgramCourse, arg.ProgramID, arg.CourseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSectionTeacher = `-- name: DeleteSectionTeacher :execrows
DELETE FROM section_teachers
WHERE section_id = $1 AND teacher_id = $2
`

type DeleteSectionTeacherParams struct {
	SectionID pgtype.UUID
	TeacherID pgtype.UUID
}

func (q *Queries) DeleteSectionTeacher(ctx context.Context, arg DeleteSectionTeacherParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSectionTeacher, arg.SectionID, arg.TeacherID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAcademicPeriod = `-- name: GetAcademicPeriod :one
SELECT id, year, term, start_date, end_date, created_at, updated_at, deleted_at, enrollment_starts_at, enrollment_ends_at FROM academic_periods
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAcademicPeriod(ctx context.Context, id pgtype.UUID) (AcademicPeriod, error) {
	row := q.db.QueryRow(ctx, getAcademicPeriod, id)
	var i AcademicPeriod
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Term,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EnrollmentStartsAt,
		&i.EnrollmentEndsAt,
	)
	return i, err
}

const getAcademicPeriodForUpdate = `-- name: GetAcademicPeriodForUpdate :one
SELECT id, year, term, start_date, end_date, created_at, updated_at, deleted_at, enrollment_starts_at, enrollment_ends_at FROM academic_periods
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) GetAcademicPeriodForUpdate(ctx context.Context, id pgtype.UUID) (AcademicPeriod, error) {
	row := q.db.QueryRow(ctx, getAcademicPeriodForUpdate, id)
	var i AcademicPeriod
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Term,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EnrollmentStartsAt,
		&i.EnrollmentEndsAt,
	)
	return i, err
}

const getCourse = `-- name: GetCourse :one
SELECT id, code, name, credits, created_at, updated_at, deleted_at, created_by, updated_by FROM courses
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCourse(ctx context.Context, id pgtype.UUID) (Course, error) {
	row := q.db.QueryRow(ctx, getCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Credits,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getCourseForUpdate = `-- name: GetCourseForUpdate :one
SELECT id, code, name, credits, created_at, updated_at, deleted_at, created_by, updated_by FROM courses
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) GetCourseForUpdate(ctx context.Context, id pgtype.UUID) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseForUpdate, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Credits,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getProgram = `-- name: GetProgram :one
SELECT id, code, name, created_at, updated_at, deleted_at, created_by, updated_by FROM programs
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProgram(ctx context.Context, id pgtype.UUID) (Program, error) {
	row := q.db.QueryRow(ctx, getProgram, id)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getProgramForUpdate = `-- name: GetProgramForUpdate :one
SELECT id, code, name, created_at, updated_at, deleted_at, created_by, updated_by FROM programs
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) GetProgramForUpdate(ctx context.Context, id pgtype.UUID) (Program, error) {
	row := q.db.QueryRow(ctx, getProgramForUpdate, id)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getProgramQuota = `-- name: GetProgramQuota :one
SELECT id, program_id, year, capacity, created_at, updated_at, deleted_at, created_by, updated_by FROM program_quotas
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProgramQuota(ctx context.Context, id pgtype.UUID) (ProgramQuota, error) {
	row := q.db.QueryRow(ctx, getProgramQuota, id)
	var i ProgramQuota
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.Year,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getSection = `-- name: GetSection :one
SELECT id, course_id, academic_period_id, capacity, created_at, updated_at, deleted_at, created_by, updated_by FROM sections
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSection(ctx context.Context, id pgtype.UUID) (Section, error) {
	row := q.db.QueryRow(ctx, getSection, id)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.AcademicPeriodID,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getSectionForUpdate = `-- name: GetSectionForUpdate :one
SELECT id, course_id, academic_period_id, capacity, created_at, updated_at, deleted_at, created_by, updated_by FROM sections
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) GetSectionForUpdate(ctx context.Context, id pgtype.UUID) (Section, error) {
	row := q.db.QueryRow(ctx, getSectionForUpdate, id)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.AcademicPeriodID,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const insertAcademicPeriod = `-- name: InsertAcademicPeriod :one

INSERT INTO academic_periods (year, term, start_date, end_date)
VALUES ($1, $2, $3, $4)
RETURNING id, year, term, start_date, end_date, created_at, updated_at, deleted_at, enrollment_starts_at, enrollment_ends_at
`

type InsertAcademicPeriodParams struct {
	Year      int32
	Term      int32
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

// Academic periods
func (q *Queries) InsertAcademicPeriod(ctx context.Context, arg InsertAcademicPeriodParams) (AcademicPeriod, error) {
	row := q.db.QueryRow(ctx, insertAcademicPeriod,
		arg.Year,
		arg.Term,
		arg.StartDate,
		arg.EndDate,
	)
	var i AcademicPeriod
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Term,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EnrollmentStartsAt,
		&i.EnrollmentEndsAt,
	)
	return i, err
}

const insertCourse = `-- name: InsertCourse :one

INSERT INTO courses (code, name, credits, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, name, credits, created_at, updated_at, deleted_at, created_by, updated_by
`

type InsertCourseParams struct {
	Code      string
	Name      string
	Credits   int32
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
}

// Courses
func (q *Queries) InsertCourse(ctx context.Context, arg InsertCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, insertCourse,
		arg.Code,
		arg.Name,
		arg.Credits,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Credits,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const insertProgram = `-- name: InsertProgram :one

INSERT INTO programs (code, name, created_by, updated_by)
VALUES ($1, $2, $3, $4)
RETURNING id, code, name, created_at, updated_at, deleted_at, created_by, updated_by
`

type InsertProgramParams struct {
	Code      string
	Name      string
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
}

// Programs
func (q *Queries) InsertProgram(ctx context.Context, arg InsertProgramParams) (Program, error) {
	row := q.db.QueryRow(ctx, insertProgram,
		arg.Code,
		arg.Name,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const insertProgramCourse = `-- name: InsertProgramCourse :one

INSERT INTO program_courses (program_id, course_id)
VALUES ($1, $2)
RETURNING program_id, course_id, created_at
`

type InsertProgramCourseParams struct {
	ProgramID pgtype.UUID
	CourseID  pgtype.UUID
}

// Program courses (M:N append-only)
func (q *Queries) InsertProgramCourse(ctx context.Context, arg InsertProgramCourseParams) (ProgramCourse, error) {
	row := q.db.QueryRow(ctx, insertProgramCourse, arg.ProgramID, arg.CourseID)
	var i ProgramCourse
	err := row.Scan(&i.ProgramID, &i.CourseID, &i.CreatedAt)
	return i, err
}

const insertSection = `-- name: InsertSection :one

INSERT INTO sections (course_id, academic_period_id, capacity, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, course_id, academic_period_id, capacity, created_at, updated_at, deleted_at, created_by, updated_by
`

type InsertSectionParams struct {
	CourseID         pgtype.UUID
	AcademicPeriodID pgtype.UUID
	Capacity         int32
	CreatedBy        pgtype.UUID
	UpdatedBy        pgtype.UUID
}

// Sections
func (q *Queries) InsertSection(ctx context.Context, arg InsertSectionParams) (Section, error) {
	row := q.db.QueryRow(ctx, insertSection,
		arg.CourseID,
		arg.AcademicPeriodID,
		arg.Capacity,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.AcademicPeriodID,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const insertSectionTeacher = `-- name: InsertSectionTeacher :one

INSERT INTO section_teachers (section_id, teacher_id)
VALUES ($1, $2)
RETURNING section_id, teacher_id, created_at
`

type InsertSectionTeacherParams struct {
	SectionID pgtype.UUID
	TeacherID pgtype.UUID
}

// Section teachers (M:N append-only)
func (q *Queries) InsertSectionTeacher(ctx context.Context, arg InsertSectionTeacherParams) (SectionTeacher, error) {
	row := q.db.QueryRow(ctx, insertSectionTeacher, arg.SectionID, arg.TeacherID)
	var i SectionTeacher
	err := row.Scan(&i.SectionID, &i.TeacherID, &i.CreatedAt)
	return i, err
}

const listAcademicPeriods = `-- name: ListAcademicPeriods :many
SELECT id, year, term, start_date, end_date, created_at, updated_at, deleted_at, enrollment_starts_at, enrollment_ends_at FROM academic_periods
WHERE deleted_at IS NULL
ORDER BY year, term
`

func (q *Queries) ListAcademicPeriods(ctx context.Context) ([]AcademicPeriod, error) {
	rows, err := q.db.Query(ctx, listAcademicPeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcademicPeriod
	for rows.Next() {
		var i AcademicPeriod
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.Term,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.EnrollmentStartsAt,
			&i.EnrollmentEndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourses = `-- name: ListCourses :many
SELECT id, code, name, credits, created_at, updated_at, deleted_at, created_by, updated_by FROM courses
WHERE deleted_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Credits,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramCoursesWithCourse = `-- name: ListProgramCoursesWithCourse :many
SELECT
    pc.program_id,
    pc.course_id,
    pc.created_at        AS association_created_at,
    c.id                 AS c_id,
    c.code               AS c_code,
    c.name               AS c_name,
    c.credits            AS c_credits,
    c.created_at         AS c_created_at,
    c.updated_at         AS c_updated_at,
    c.deleted_at         AS c_deleted_at,
    c.created_by         AS c_created_by,
    c.updated_by         AS c_updated_by
FROM program_courses pc
JOIN courses c ON c.id = pc.course_id AND c.deleted_at IS NULL
WHERE pc.program_id = $1
ORDER BY pc.created_at
`

type ListProgramCoursesWithCourseRow struct {
	ProgramID            pgtype.UUID
	CourseID             pgtype.UUID
	AssociationCreatedAt pgtype.Timestamptz
	CID                  pgtype.UUID
	CCode                string
	CName                string
	CCredits             int32
	CCreatedAt           pgtype.Timestamptz
	CUpdatedAt           pgtype.Timestamptz
	CDeletedAt           pgtype.Timestamptz
	CCreatedBy           pgtype.UUID
	CUpdatedBy           pgtype.UUID
}

func (q *Queries) ListProgramCoursesWithCourse(ctx context.Context, programID pgtype.UUID) ([]ListProgramCoursesWithCourseRow, error) {
	rows, err := q.db.Query(ctx, listProgramCoursesWithCourse, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProgramCoursesWithCourseRow
	for rows.Next() {
		var i ListProgramCoursesWithCourseRow
		if err := rows.Scan(
			&i.ProgramID,
			&i.CourseID,
			&i.AssociationCreatedAt,
			&i.CID,
			&i.CCode,
			&i.CName,
			&i.CCredits,
			&i.CCreatedAt,
			&i.CUpdatedAt,
			&i.CDeletedAt,
			&i.CCreatedBy,
			&i.CUpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramQuotas = `-- name: ListProgramQuotas :many
SELECT id, program_id, year, capacity, created_at, updated_at, deleted_at, created_by, updated_by FROM program_quotas
WHERE program_id = $1 AND deleted_at IS NULL
ORDER BY year
`

func (q *Queries) ListProgramQuotas(ctx context.Context, programID pgtype.UUID) ([]ProgramQuota, error) {
	rows, err := q.db.Query(ctx, listProgramQuotas, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProgramQuota
	for rows.Next() {
		var i ProgramQuota
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.Year,
			&i.Capacity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrograms = `-- name: ListPrograms :many
SELECT id, code, name, created_at, updated_at, deleted_at, created_by, updated_by FROM programs
WHERE deleted_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListPrograms(ctx context.Context) ([]Program, error) {
	rows, err := q.db.Query(ctx, listPrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Program
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionTeachers = `-- name: ListSectionTeachers :many
SELECT section_id, teacher_id, created_at FROM section_teachers
WHERE section_id = $1
ORDER BY created_at
`

func (q *Queries) ListSectionTeachers(ctx context.Context, sectionID pgtype.UUID) ([]SectionTeacher, error) {
	rows, err := q.db.Query(ctx, listSectionTeachers, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SectionTeacher
	for rows.Next() {
		var i SectionTeacher
		if err := rows.Scan(&i.SectionID, &i.TeacherID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSections = `-- name: ListSections :many
SELECT id, course_id, academic_period_id, capacity, created_at, updated_at, deleted_at, created_by, updated_by FROM sections
WHERE deleted_at IS NULL
  AND ($1::uuid IS NULL OR course_id = $1::uuid)
  AND ($2::uuid IS NULL OR academic_period_id = $2::uuid)
ORDER BY created_at
`

type ListSectionsParams struct {
	CourseID         pgtype.UUID
	AcademicPeriodID pgtype.UUID
}

func (q *Queries) ListSections(ctx context.Context, arg ListSectionsParams) ([]Section, error) {
	rows, err := q.db.Query(ctx, listSections, arg.CourseID, arg.AcademicPeriodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Section
	for rows.Next() {
		var i Section
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.AcademicPeriodID,
			&i.Capacity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAcademicPeriod = `-- name: SoftDeleteAcademicPeriod :execrows
UPDATE academic_periods
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAcademicPeriod(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAcademicPeriod, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteCourse = `-- name: SoftDeleteCourse :execrows
UPDATE courses
SET deleted_at = now(), updated_at = now(), updated_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteCourseParams struct {
	ID        pgtype.UUID
	UpdatedBy pgtype.UUID
}

func (q *Queries) SoftDeleteCourse(ctx context.Context, arg SoftDeleteCourseParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteCourse, arg.ID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteProgram = `-- name: SoftDeleteProgram :execrows
UPDATE programs
SET deleted_at = now(), updated_at = now(), updated_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteProgramParams struct {
	ID        pgtype.UUID
	UpdatedBy pgtype.UUID
}

func (q *Queries) SoftDeleteProgram(ctx context.Context, arg SoftDeleteProgramParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProgram, arg.ID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteProgramQuota = `-- name: SoftDeleteProgramQuota :execrows
UPDATE program_quotas
SET deleted_at = now(), updated_at = now(), updated_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteProgramQuotaParams struct {
	ID        pgtype.UUID
	UpdatedBy pgtype.UUID
}

func (q *Queries) SoftDeleteProgramQuota(ctx context.Context, arg SoftDeleteProgramQuotaParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProgramQuota, arg.ID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteSection = `-- name: SoftDeleteSection :execrows
UPDATE sections
SET deleted_at = now(), updated_at = now(), updated_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteSectionParams struct {
	ID        pgtype.UUID
	UpdatedBy pgtype.UUID
}

func (q *Queries) SoftDeleteSection(ctx context.Context, arg SoftDeleteSectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteSection, arg.ID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAcademicPeriod = `-- name: UpdateAcademicPeriod :one
UPDATE academic_periods
SET year = $2, term = $3, start_date = $4, end_date = $5, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, year, term, start_date, end_date, created_at, updated_at, deleted_at, enrollment_starts_at, enrollment_ends_at
`

type UpdateAcademicPeriodParams struct {
	ID        pgtype.UUID
	Year      int32
	Term      int32
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

func (q *Queries) UpdateAcademicPeriod(ctx context.Context, arg UpdateAcademicPeriodParams) (AcademicPeriod, error) {
	row := q.db.QueryRow(ctx, updateAcademicPeriod,
		arg.ID,
		arg.Year,
		arg.Term,
		arg.StartDate,
		arg.EndDate,
	)
	var i AcademicPeriod
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Term,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EnrollmentStartsAt,
		&i.EnrollmentEndsAt,
	)
	return i, err
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses
SET code = $2, name = $3, credits = $4, updated_at = now(), updated_by = $5
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, name, credits, created_at, updated_at, deleted_at, created_by, updated_by
`

type UpdateCourseParams struct {
	ID        pgtype.UUID
	Code      string
	Name      string
	Credits   int32
	UpdatedBy pgtype.UUID
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Credits,
		arg.UpdatedBy,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Credits,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateProgram = `-- name: UpdateProgram :one
UPDATE programs
SET code = $2, name = $3, updated_at = now(), updated_by = $4
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, name, created_at, updated_at, deleted_at, created_by, updated_by
`

type UpdateProgramParams struct {
	ID        pgtype.UUID
	Code      string
	Name      string
	UpdatedBy pgtype.UUID
}

func (q *Queries) UpdateProgram(ctx context.Context, arg UpdateProgramParams) (Program, error) {
	row := q.db.QueryRow(ctx, updateProgram,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.UpdatedBy,
	)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateProgramQuota = `-- name: UpdateProgramQuota :one
UPDATE program_quotas
SET year = $2, capacity = $3, updated_at = now(), updated_by = $4
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, program_id, year, capacity, created_at, updated_at, deleted_at, created_by, updated_by
`

type UpdateProgramQuotaParams struct {
	ID        pgtype.UUID
	Year      int32
	Capacity  int32
	UpdatedBy pgtype.UUID
}

func (q *Queries) UpdateProgramQuota(ctx context.Context, arg UpdateProgramQuotaParams) (ProgramQuota, error) {
	row := q.db.QueryRow(ctx, updateProgramQuota,
		arg.ID,
		arg.Year,
		arg.Capacity,
		arg.UpdatedBy,
	)
	var i ProgramQuota
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.Year,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateSection = `-- name: UpdateSection :one
UPDATE sections
SET capacity = $2, updated_at = now(), updated_by = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, course_id, academic_period_id, capacity, created_at, updated_at, deleted_at, created_by, updated_by
`

type UpdateSectionParams struct {
	ID        pgtype.UUID
	Capacity  int32
	UpdatedBy pgtype.UUID
}

func (q *Queries) UpdateSection(ctx context.Context, arg UpdateSectionParams) (Section, error) {
	row := q.db.QueryRow(ctx, updateSection, arg.ID, arg.Capacity, arg.UpdatedBy)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.AcademicPeriodID,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertProgramQuota = `-- name: UpsertProgramQuota :one

INSERT INTO program_quotas (program_id, year, capacity, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (program_id, year) DO UPDATE
  SET capacity   = EXCLUDED.capacity,
      updated_at = now(),
      updated_by = EXCLUDED.updated_by,
      deleted_at = NULL
RETURNING id, program_id, year, capacity, created_at, updated_at, deleted_at, created_by, updated_by
`

type UpsertProgramQuotaParams struct {
	ProgramID pgtype.UUID
	Year      int32
	Capacity  int32
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
}

// Program quotas
func (q *Queries) UpsertProgramQuota(ctx context.Context, arg UpsertProgramQuotaParams) (ProgramQuota, error) {
	row := q.db.QueryRow(ctx, upsertProgramQuota,
		arg.ProgramID,
		arg.Year,
		arg.Capacity,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i ProgramQuota
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.Year,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
