// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package rbacdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Permission struct {
	ID          pgtype.UUID
	Code        string
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Role struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RolePermission struct {
	RoleID       pgtype.UUID
	PermissionID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	CreatedBy    pgtype.UUID
	UpdatedBy    pgtype.UUID
	DeletedAt    pgtype.Timestamptz
}

type UserRole struct {
	UserID    pgtype.UUID
	RoleID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}
