// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package rbacdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// DISTINCT is required: a user with multiple roles that share a permission would otherwise
	// produce duplicate rows, one per (role, permission) combination.
	GetPermissionsForUser(ctx context.Context, userID pgtype.UUID) ([]string, error)
}

var _ Querier = (*Queries)(nil)
