// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package section_enrollmentdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AcademicPeriod struct {
	ID                 pgtype.UUID
	Year               int32
	Term               int32
	StartDate          pgtype.Date
	EndDate            pgtype.Date
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
	EnrollmentStartsAt pgtype.Timestamptz
	EnrollmentEndsAt   pgtype.Timestamptz
}

type AuditLog struct {
	ID        pgtype.UUID
	ActorID   pgtype.UUID
	Action    string
	Entity    string
	EntityID  pgtype.UUID
	Detail    []byte
	CreatedAt pgtype.Timestamptz
}

type Course struct {
	ID        pgtype.UUID
	Code      string
	Name      string
	Credits   int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
}

type Enrollment struct {
	ID        pgtype.UUID
	StudentID pgtype.UUID
	ProgramID pgtype.UUID
	Year      int32
	Status    string
	PaidAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
}

type Evaluation struct {
	ID        pgtype.UUID
	CourseID  pgtype.UUID
	Weight    pgtype.Numeric
	Position  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Grade struct {
	ID                  pgtype.UUID
	EvaluationID        pgtype.UUID
	SectionEnrollmentID pgtype.UUID
	GradedBy            pgtype.UUID
	Value               pgtype.Numeric
	EvaluatedAt         pgtype.Timestamptz
	Version             int32
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	CreatedBy           pgtype.UUID
	UpdatedBy           pgtype.UUID
	DeletedAt           pgtype.Timestamptz
}

type Permission struct {
	ID          pgtype.UUID
	Code        string
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Program struct {
	ID        pgtype.UUID
	Code      string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
}

type ProgramCourse struct {
	ProgramID pgtype.UUID
	CourseID  pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type ProgramQuota struct {
	ID        pgtype.UUID
	ProgramID pgtype.UUID
	Year      int32
	Capacity  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
}

type Role struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RolePermission struct {
	RoleID       pgtype.UUID
	PermissionID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

type Section struct {
	ID               pgtype.UUID
	CourseID         pgtype.UUID
	AcademicPeriodID pgtype.UUID
	Capacity         int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	CreatedBy        pgtype.UUID
	UpdatedBy        pgtype.UUID
}

type SectionEnrollment struct {
	ID           pgtype.UUID
	EnrollmentID pgtype.UUID
	SectionID    pgtype.UUID
	Status       string
	RegisteredAt pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	FinalGrade   pgtype.Numeric
}

type SectionTeacher struct {
	SectionID pgtype.UUID
	TeacherID pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type StudentProfile struct {
	UserID        pgtype.UUID
	AdmissionYear int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	CreatedBy     pgtype.UUID
	UpdatedBy     pgtype.UUID
}

type TeacherProfile struct {
	UserID     pgtype.UUID
	Department pgtype.Text
	Title      pgtype.Text
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	CreatedBy  pgtype.UUID
	UpdatedBy  pgtype.UUID
}

type TeacherQualification struct {
	ID        pgtype.UUID
	TeacherID pgtype.UUID
	Degree    string
	Year      int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	CreatedBy    pgtype.UUID
	UpdatedBy    pgtype.UUID
	DeletedAt    pgtype.Timestamptz
}

type UserProfile struct {
	UserID                pgtype.UUID
	GivenNames            string
	LastNamePaternal      string
	LastNameMaternal      pgtype.Text
	NationalIDType        string
	NationalID            string
	BirthDate             pgtype.Date
	Phone                 pgtype.Text
	PersonalEmail         pgtype.Text
	AddressStreet         pgtype.Text
	Commune               pgtype.Text
	Region                pgtype.Text
	Country               pgtype.Text
	PostalCode            pgtype.Text
	Sex                   pgtype.Text
	Nationality           pgtype.Text
	PhotoUrl              pgtype.Text
	EmergencyContactName  pgtype.Text
	EmergencyContactPhone pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
	CreatedBy             pgtype.UUID
	UpdatedBy             pgtype.UUID
}

type UserRole struct {
	UserID    pgtype.UUID
	RoleID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}
