// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sectionenrollmentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Non-locking snapshot count of active inscriptions for pre-check fast-fail.
	// Uses the partial index section_enrollments_active_seat_idx.
	// NOT authoritative — the under-lock count is the source of truth.
	CountActiveSeats(ctx context.Context, sectionID pgtype.UUID) (int64, error)
	// Checks whether a course belongs to a program's course list.
	// Returns a boolean; false (no row) means the course is not in the program.
	CourseInProgram(ctx context.Context, arg CourseInProgramParams) (bool, error)
	// Cross-domain read strategy: queries here read enrollment, sections, academic_periods,
	// and program_courses schema directly. Coupling is to the shared migration schema, not
	// to Go service layers. The single transaction boundary is what makes paid+program+seat
	// checks atomic. This is the canonical approach for this codebase.
	// Non-locking read of section capacity and course_id.
	// Used for the pre-check fast-fail BEFORE BeginTx; avoids acquiring the row lock
	// for sections that are obviously full or missing. Returns ErrNoRows when absent.
	GetSectionCapacity(ctx context.Context, id pgtype.UUID) (GetSectionCapacityRow, error)
	GetSectionEnrollmentByID(ctx context.Context, id pgtype.UUID) (SectionEnrollment, error)
	// Fetches a LIVE inscription row for (enrollment_id, section_id) with a FOR UPDATE lock
	// for revival detection. Filters deleted_at IS NULL so that a soft-deleted row never
	// triggers AlreadyExists or revival logic. Lock order: acquired after section lock.
	GetSectionEnrollmentByKeyForUpdate(ctx context.Context, arg GetSectionEnrollmentByKeyForUpdateParams) (SectionEnrollment, error)
	// Locks the section row FOR UPDATE and fetches capacity, course_id, period_year, and
	// whether now() falls within the academic period's enrollment window (inclusive on both ends).
	// window_open=false when the window is not configured (fail-closed).
	// period_year is used by the caller to enforce that the linked enrollment matches
	// the section's academic year before inserting.
	// Used as lock step #1 in EnrollSectionTx; lock order is section → key row.
	GetSectionForUpdateWithWindow(ctx context.Context, id pgtype.UUID) (GetSectionForUpdateWithWindowRow, error)
	InsertSectionEnrollment(ctx context.Context, arg InsertSectionEnrollmentParams) (SectionEnrollment, error)
	// Returns sections a student may self-enroll into, applying all five eligibility gates
	// in a single query (no N+1):
	//   1. The student has a PAID enrollment in a program whose course list includes the section.
	//   2. The section's academic period year matches the enrollment's year.
	//   3. The enrollment window is OPEN (now() BETWEEN starts_at AND ends_at, NULL → fail-closed).
	//   4. There is available capacity (active seats < capacity).
	//   5. The student is not already actively enrolled in the section.
	//
	// Seat availability is computed as capacity - active_seat_count; the active-seat count is
	// obtained via a correlated subquery that leverages section_enrollments_active_seat_idx.
	// Stable ORDER BY: period_year DESC, course_code ASC, section_id ASC ensures deterministic
	// keyset pagination across pages.
	// The keyset cursor is (period_year DESC, course_code ASC, section_id ASC); page_token
	// encodes the last seen (period_year, course_code, section_id) as three pipe-delimited fields.
	// To keep the cursor simple and avoid composite type complexity in sqlc, we use a separate
	// page_token_section_id UUID column parameter combined with the other sort fields.
	// Simpler approach: use section_id UUID as the sole cursor (UUIDv7 embeds timestamp, which
	// within a year+code group gives a stable order). We ORDER BY s.id ASC as tie-breaker and
	// use s.id as the cursor so the keyset condition is simply s.id > page_token.
	// NOTE: We switch the stable sort to (period_year DESC, course_code ASC, s.id ASC) and use
	// s.id as the cursor. Since UUIDv7 is monotone by insertion time, this gives a stable order
	// within a (year, course) group. Between (year, course) groups, s.id alone is not sufficient
	// as a cursor, so we use a compound cursor: callers must restart from the last seen s.id
	// within the last (year, code) group. This is an acceptable tradeoff for a discovery endpoint.
	// For simplicity, we use s.id as the sole keyset cursor (exclusive lower bound) which is
	// correct when results are ordered by s.id ASC globally. We therefore order by s.id ASC only.
	ListEnrollableSections(ctx context.Context, arg ListEnrollableSectionsParams) ([]ListEnrollableSectionsRow, error)
	// Returns live inscriptions for a student by joining enrollments on student_id.
	// Keyset pagination: results ordered by se.id DESC; page_token is the exclusive upper bound.
	ListOwnSectionEnrollments(ctx context.Context, arg ListOwnSectionEnrollmentsParams) ([]SectionEnrollment, error)
	// Returns live inscriptions for a student enriched with course name/code and academic period
	// year/term via JOINs on sections, courses, and academic_periods.
	// Used only by ListOwnSectionEnrollments RPC; other RPCs use queries that do not project these columns.
	// Keyset pagination: results ordered by se.id DESC; page_token is the exclusive upper bound.
	ListOwnSectionEnrollmentsEnriched(ctx context.Context, arg ListOwnSectionEnrollmentsEnrichedParams) ([]ListOwnSectionEnrollmentsEnrichedRow, error)
	ListSectionEnrollments(ctx context.Context, arg ListSectionEnrollmentsParams) ([]SectionEnrollment, error)
	// Returns live section_enrollment rows for a section the caller teaches, with student_id
	// projected from the linked enrollment.
	// EXISTS guard: if the caller is not in section_teachers for the section, returns no rows
	// (anti-leak: existence is never disclosed — empty page, not PermissionDenied).
	// Includes withdrawn enrollments (status distinguishes them from active ones).
	// Keyset pagination on se.id DESC; page_token is the exclusive upper bound.
	// Cross-domain read: reads section_teachers (catalog schema) and enrollments.
	// This is the same intra-DB coupling already established in this context (see file header).
	ListSectionRosterForTeacher(ctx context.Context, arg ListSectionRosterForTeacherParams) ([]ListSectionRosterForTeacherRow, error)
	// Returns live section_enrollment rows for a section WITHOUT the section_teachers EXISTS
	// guard. Used by the admin bypass so callers holding enrollment.manage can see the full
	// roster regardless of whether they are assigned as a teacher.
	// Includes withdrawn enrollments (status distinguishes them from active ones).
	// Keyset pagination on se.id DESC; page_token is the exclusive upper bound.
	// Cross-domain read: reads enrollments table — same intra-DB coupling as the teacher variant.
	ListSectionRosterForTeacherAll(ctx context.Context, arg ListSectionRosterForTeacherAllParams) ([]ListSectionRosterForTeacherAllRow, error)
	// Resolves an enrollment by id without filtering on status.
	// Returns year, status, and deleted_at so the caller can distinguish:
	//   not found / soft-deleted → ErrNotFound
	//   found but status != 'paid' → ErrNotPaid
	//   found but year ≠ section period year → ErrEnrollmentYearMismatch
	ResolveEnrollmentByID(ctx context.Context, id pgtype.UUID) (ResolveEnrollmentByIDRow, error)
	// Resolves an enrollment for a student in a specific program and year.
	// Returns the full status and deleted_at so the caller can distinguish:
	//   not found / soft-deleted → ErrNotFound
	//   found but status != 'paid' → ErrNotPaid
	// The year parameter must equal the section's academic period year so that a
	// matrícula from a different year cannot satisfy a section in another year.
	ResolveEnrollmentByStudentAndProgram(ctx context.Context, arg ResolveEnrollmentByStudentAndProgramParams) (ResolveEnrollmentByStudentAndProgramRow, error)
	// Revives a withdrawn inscription: sets status back to in_progress and clears deleted_at.
	ReviveSectionEnrollment(ctx context.Context, id pgtype.UUID) (SectionEnrollment, error)
	// Transitions a section_enrollment status to passed or failed and writes the
	// computed final grade, within a caller-owned transaction.
	// Source states in_progress/passed/failed are all valid (allows passed<->failed flips).
	// withdrawn source is rejected (0 rows returned — treated as ErrInvalidTransition).
	// Target must be passed or failed; in_progress is not a valid target.
	SetSectionEnrollmentOutcome(ctx context.Context, arg SetSectionEnrollmentOutcomeParams) (SectionEnrollment, error)
	// Transitions an in_progress inscription to withdrawn.
	// Sets updated_at; does NOT set deleted_at — withdrawn rows are retained for audit/revival.
	WithdrawSectionEnrollment(ctx context.Context, id pgtype.UUID) (SectionEnrollment, error)
}

var _ Querier = (*Queries)(nil)
