// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sectionenrollmentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSeats = `-- name: CountActiveSeats :one
SELECT count(*)
FROM section_enrollments
WHERE section_id = $1
  AND status <> 'withdrawn'
  AND deleted_at IS NULL
`

// Non-locking snapshot count of active inscriptions for pre-check fast-fail.
// Uses the partial index section_enrollments_active_seat_idx.
// NOT authoritative — the under-lock count is the source of truth.
func (q *Queries) CountActiveSeats(ctx context.Context, sectionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSeats, sectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const courseInProgram = `-- name: CourseInProgram :one
SELECT EXISTS(
    SELECT 1 FROM program_courses
    WHERE program_id = $1 AND course_id = $2
) AS exists
`

type CourseInProgramParams struct {
	ProgramID pgtype.UUID
	CourseID  pgtype.UUID
}

// Checks whether a course belongs to a program's course list.
// Returns a boolean; false (no row) means the course is not in the program.
func (q *Queries) CourseInProgram(ctx context.Context, arg CourseInProgramParams) (bool, error) {
	row := q.db.QueryRow(ctx, courseInProgram, arg.ProgramID, arg.CourseID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getSectionCapacity = `-- name: GetSectionCapacity :one

SELECT
    s.capacity,
    s.course_id
FROM sections s
WHERE s.id = $1 AND s.deleted_at IS NULL
`

type GetSectionCapacityRow struct {
	Capacity int32
	CourseID pgtype.UUID
}

// Cross-domain read strategy: queries here read enrollment, sections, academic_periods,
// and program_courses schema directly. Coupling is to the shared migration schema, not
// to Go service layers. The single transaction boundary is what makes paid+program+seat
// checks atomic. This is the canonical approach for this codebase.
// Non-locking read of section capacity and course_id.
// Used for the pre-check fast-fail BEFORE BeginTx; avoids acquiring the row lock
// for sections that are obviously full or missing. Returns ErrNoRows when absent.
func (q *Queries) GetSectionCapacity(ctx context.Context, id pgtype.UUID) (GetSectionCapacityRow, error) {
	row := q.db.QueryRow(ctx, getSectionCapacity, id)
	var i GetSectionCapacityRow
	err := row.Scan(&i.Capacity, &i.CourseID)
	return i, err
}

const getSectionEnrollmentByID = `-- name: GetSectionEnrollmentByID :one
SELECT id, enrollment_id, section_id, status, registered_at, created_at, updated_at, deleted_at, final_grade FROM section_enrollments
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSectionEnrollmentByID(ctx context.Context, id pgtype.UUID) (SectionEnrollment, error) {
	row := q.db.QueryRow(ctx, getSectionEnrollmentByID, id)
	var i SectionEnrollment
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.SectionID,
		&i.Status,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FinalGrade,
	)
	return i, err
}

const getSectionEnrollmentByKeyForUpdate = `-- name: GetSectionEnrollmentByKeyForUpdate :one
SELECT id, enrollment_id, section_id, status, registered_at, created_at, updated_at, deleted_at, final_grade FROM section_enrollments
WHERE enrollment_id = $1 AND section_id = $2 AND deleted_at IS NULL
FOR UPDATE
`

type GetSectionEnrollmentByKeyForUpdateParams struct {
	EnrollmentID pgtype.UUID
	SectionID    pgtype.UUID
}

// Fetches a LIVE inscription row for (enrollment_id, section_id) with a FOR UPDATE lock
// for revival detection. Filters deleted_at IS NULL so that a soft-deleted row never
// triggers AlreadyExists or revival logic. Lock order: acquired after section lock.
func (q *Queries) GetSectionEnrollmentByKeyForUpdate(ctx context.Context, arg GetSectionEnrollmentByKeyForUpdateParams) (SectionEnrollment, error) {
	row := q.db.QueryRow(ctx, getSectionEnrollmentByKeyForUpdate, arg.EnrollmentID, arg.SectionID)
	var i SectionEnrollment
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.SectionID,
		&i.Status,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FinalGrade,
	)
	return i, err
}

const getSectionForUpdateWithWindow = `-- name: GetSectionForUpdateWithWindow :one
SELECT
    s.capacity,
    s.course_id,
    ap.year AS period_year,
    (
        ap.enrollment_starts_at IS NOT NULL
        AND ap.enrollment_ends_at IS NOT NULL
        AND now() BETWEEN ap.enrollment_starts_at AND ap.enrollment_ends_at
    ) AS window_open
FROM sections s
JOIN academic_periods ap ON ap.id = s.academic_period_id
WHERE s.id = $1 AND s.deleted_at IS NULL
FOR UPDATE OF s
`

type GetSectionForUpdateWithWindowRow struct {
	Capacity   int32
	CourseID   pgtype.UUID
	PeriodYear int32
	WindowOpen pgtype.Bool
}

// Locks the section row FOR UPDATE and fetches capacity, course_id, period_year, and
// whether now() falls within the academic period's enrollment window (inclusive on both ends).
// window_open=false when the window is not configured (fail-closed).
// period_year is used by the caller to enforce that the linked enrollment matches
// the section's academic year before inserting.
// Used as lock step #1 in EnrollSectionTx; lock order is section → key row.
func (q *Queries) GetSectionForUpdateWithWindow(ctx context.Context, id pgtype.UUID) (GetSectionForUpdateWithWindowRow, error) {
	row := q.db.QueryRow(ctx, getSectionForUpdateWithWindow, id)
	var i GetSectionForUpdateWithWindowRow
	err := row.Scan(
		&i.Capacity,
		&i.CourseID,
		&i.PeriodYear,
		&i.WindowOpen,
	)
	return i, err
}

const insertSectionEnrollment = `-- name: InsertSectionEnrollment :one
INSERT INTO section_enrollments (enrollment_id, section_id, status)
VALUES ($1, $2, 'in_progress')
RETURNING id, enrollment_id, section_id, status, registered_at, created_at, updated_at, deleted_at, final_grade
`

type InsertSectionEnrollmentParams struct {
	EnrollmentID pgtype.UUID
	SectionID    pgtype.UUID
}

func (q *Queries) InsertSectionEnrollment(ctx context.Context, arg InsertSectionEnrollmentParams) (SectionEnrollment, error) {
	row := q.db.QueryRow(ctx, insertSectionEnrollment, arg.EnrollmentID, arg.SectionID)
	var i SectionEnrollment
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.SectionID,
		&i.Status,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FinalGrade,
	)
	return i, err
}

const listEnrollableSections = `-- name: ListEnrollableSections :many
SELECT
    s.id                                                                     AS section_id,
    e.program_id,
    c.name                                                                   AS course_name,
    c.code                                                                   AS course_code,
    ap.year                                                                  AS period_year,
    ap.term                                                                  AS period_term,
    (s.capacity - (
        SELECT count(*)
        FROM section_enrollments sea
        WHERE sea.section_id = s.id
          AND sea.status <> 'withdrawn'
          AND sea.deleted_at IS NULL
    ))::int                                                                  AS seats_available
FROM enrollments e
JOIN program_courses pc   ON pc.program_id = e.program_id
JOIN courses       c      ON c.id           = pc.course_id AND c.deleted_at IS NULL
JOIN sections      s      ON s.course_id    = c.id         AND s.deleted_at IS NULL
JOIN academic_periods ap  ON ap.id          = s.academic_period_id AND ap.deleted_at IS NULL
LEFT JOIN section_enrollments se_own
    ON se_own.section_id    = s.id
    AND se_own.enrollment_id = e.id
    AND se_own.status        <> 'withdrawn'
    AND se_own.deleted_at    IS NULL
WHERE e.student_id = $1::uuid
  AND e.status     = 'paid'
  AND e.deleted_at IS NULL
  AND e.year       = ap.year
  AND ap.enrollment_starts_at IS NOT NULL
  AND ap.enrollment_ends_at   IS NOT NULL
  AND now() BETWEEN ap.enrollment_starts_at AND ap.enrollment_ends_at
  AND s.capacity > (
        SELECT count(*)
        FROM section_enrollments sac
        WHERE sac.section_id = s.id
          AND sac.status <> 'withdrawn'
          AND sac.deleted_at IS NULL
    )
  AND se_own.section_id IS NULL
  AND ($2::uuid IS NULL OR s.id > $2::uuid)
ORDER BY s.id ASC
LIMIT $3::int
`

type ListEnrollableSectionsParams struct {
	StudentID pgtype.UUID
	PageToken pgtype.UUID
	RowLimit  int32
}

type ListEnrollableSectionsRow struct {
	SectionID      pgtype.UUID
	ProgramID      pgtype.UUID
	CourseName     string
	CourseCode     string
	PeriodYear     int32
	PeriodTerm     int32
	SeatsAvailable int32
}

// Returns sections a student may self-enroll into, applying all five eligibility gates
// in a single query (no N+1):
//  1. The student has a PAID enrollment in a program whose course list includes the section.
//  2. The section's academic period year matches the enrollment's year.
//  3. The enrollment window is OPEN (now() BETWEEN starts_at AND ends_at, NULL → fail-closed).
//  4. There is available capacity (active seats < capacity).
//  5. The student is not already actively enrolled in the section.
//
// Seat availability is computed as capacity - active_seat_count; the active-seat count is
// obtained via a correlated subquery that leverages section_enrollments_active_seat_idx.
// Stable ORDER BY: period_year DESC, course_code ASC, section_id ASC ensures deterministic
// keyset pagination across pages.
// The keyset cursor is (period_year DESC, course_code ASC, section_id ASC); page_token
// encodes the last seen (period_year, course_code, section_id) as three pipe-delimited fields.
// To keep the cursor simple and avoid composite type complexity in sqlc, we use a separate
// page_token_section_id UUID column parameter combined with the other sort fields.
// Simpler approach: use section_id UUID as the sole cursor (UUIDv7 embeds timestamp, which
// within a year+code group gives a stable order). We ORDER BY s.id ASC as tie-breaker and
// use s.id as the cursor so the keyset condition is simply s.id > page_token.
// NOTE: We switch the stable sort to (period_year DESC, course_code ASC, s.id ASC) and use
// s.id as the cursor. Since UUIDv7 is monotone by insertion time, this gives a stable order
// within a (year, course) group. Between (year, course) groups, s.id alone is not sufficient
// as a cursor, so we use a compound cursor: callers must restart from the last seen s.id
// within the last (year, code) group. This is an acceptable tradeoff for a discovery endpoint.
// For simplicity, we use s.id as the sole keyset cursor (exclusive lower bound) which is
// correct when results are ordered by s.id ASC globally. We therefore order by s.id ASC only.
func (q *Queries) ListEnrollableSections(ctx context.Context, arg ListEnrollableSectionsParams) ([]ListEnrollableSectionsRow, error) {
	rows, err := q.db.Query(ctx, listEnrollableSections, arg.StudentID, arg.PageToken, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnrollableSectionsRow
	for rows.Next() {
		var i ListEnrollableSectionsRow
		if err := rows.Scan(
			&i.SectionID,
			&i.ProgramID,
			&i.CourseName,
			&i.CourseCode,
			&i.PeriodYear,
			&i.PeriodTerm,
			&i.SeatsAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnSectionEnrollments = `-- name: ListOwnSectionEnrollments :many
SELECT se.id, se.enrollment_id, se.section_id, se.status, se.registered_at, se.created_at, se.updated_at, se.deleted_at, se.final_grade
FROM section_enrollments se
JOIN enrollments e ON e.id = se.enrollment_id
WHERE e.student_id = $1::uuid
  AND se.deleted_at IS NULL
  AND ($2::uuid IS NULL OR se.id < $2::uuid)
ORDER BY se.id DESC
LIMIT $3::int
`

type ListOwnSectionEnrollmentsParams struct {
	StudentID pgtype.UUID
	PageToken pgtype.UUID
	RowLimit  int32
}

// Returns live inscriptions for a student by joining enrollments on student_id.
// Keyset pagination: results ordered by se.id DESC; page_token is the exclusive upper bound.
func (q *Queries) ListOwnSectionEnrollments(ctx context.Context, arg ListOwnSectionEnrollmentsParams) ([]SectionEnrollment, error) {
	rows, err := q.db.Query(ctx, listOwnSectionEnrollments, arg.StudentID, arg.PageToken, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SectionEnrollment
	for rows.Next() {
		var i SectionEnrollment
		if err := rows.Scan(
			&i.ID,
			&i.EnrollmentID,
			&i.SectionID,
			&i.Status,
			&i.RegisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FinalGrade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnSectionEnrollmentsEnriched = `-- name: ListOwnSectionEnrollmentsEnriched :many
SELECT
    se.id, se.enrollment_id, se.section_id, se.status, se.registered_at,
    se.created_at, se.updated_at, se.deleted_at, se.final_grade,
    c.name  AS course_name,
    c.code  AS course_code,
    ap.year AS period_year,
    ap.term AS period_term
FROM section_enrollments se
JOIN enrollments e  ON e.id  = se.enrollment_id
JOIN sections    s  ON s.id  = se.section_id
JOIN courses     c  ON c.id  = s.course_id
JOIN academic_periods ap ON ap.id = s.academic_period_id
WHERE e.student_id = $1::uuid
  AND se.deleted_at IS NULL
  AND ($2::uuid IS NULL OR se.id < $2::uuid)
ORDER BY se.id DESC
LIMIT $3::int
`

type ListOwnSectionEnrollmentsEnrichedParams struct {
	StudentID pgtype.UUID
	PageToken pgtype.UUID
	RowLimit  int32
}

type ListOwnSectionEnrollmentsEnrichedRow struct {
	ID           pgtype.UUID
	EnrollmentID pgtype.UUID
	SectionID    pgtype.UUID
	Status       string
	RegisteredAt pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	FinalGrade   pgtype.Numeric
	CourseName   string
	CourseCode   string
	PeriodYear   int32
	PeriodTerm   int32
}

// Returns live inscriptions for a student enriched with course name/code and academic period
// year/term via JOINs on sections, courses, and academic_periods.
// Used only by ListOwnSectionEnrollments RPC; other RPCs use queries that do not project these columns.
// Keyset pagination: results ordered by se.id DESC; page_token is the exclusive upper bound.
func (q *Queries) ListOwnSectionEnrollmentsEnriched(ctx context.Context, arg ListOwnSectionEnrollmentsEnrichedParams) ([]ListOwnSectionEnrollmentsEnrichedRow, error) {
	rows, err := q.db.Query(ctx, listOwnSectionEnrollmentsEnriched, arg.StudentID, arg.PageToken, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnSectionEnrollmentsEnrichedRow
	for rows.Next() {
		var i ListOwnSectionEnrollmentsEnrichedRow
		if err := rows.Scan(
			&i.ID,
			&i.EnrollmentID,
			&i.SectionID,
			&i.Status,
			&i.RegisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FinalGrade,
			&i.CourseName,
			&i.CourseCode,
			&i.PeriodYear,
			&i.PeriodTerm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionEnrollments = `-- name: ListSectionEnrollments :many
SELECT id, enrollment_id, section_id, status, registered_at, created_at, updated_at, deleted_at, final_grade FROM section_enrollments
WHERE deleted_at IS NULL
  AND ($1::uuid IS NULL    OR id            < $1::uuid)
  AND ($2::uuid IS NULL    OR section_id    = $2::uuid)
  AND ($3::uuid IS NULL OR enrollment_id = $3::uuid)
  AND ($4::text IS NULL        OR status        = $4::text)
ORDER BY id DESC
LIMIT $5::int
`

type ListSectionEnrollmentsParams struct {
	PageToken    pgtype.UUID
	SectionID    pgtype.UUID
	EnrollmentID pgtype.UUID
	Status       pgtype.Text
	RowLimit     int32
}

func (q *Queries) ListSectionEnrollments(ctx context.Context, arg ListSectionEnrollmentsParams) ([]SectionEnrollment, error) {
	rows, err := q.db.Query(ctx, listSectionEnrollments,
		arg.PageToken,
		arg.SectionID,
		arg.EnrollmentID,
		arg.Status,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SectionEnrollment
	for rows.Next() {
		var i SectionEnrollment
		if err := rows.Scan(
			&i.ID,
			&i.EnrollmentID,
			&i.SectionID,
			&i.Status,
			&i.RegisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FinalGrade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionRosterForTeacher = `-- name: ListSectionRosterForTeacher :many
SELECT se.id, se.enrollment_id, se.section_id, se.status, se.registered_at,
       se.created_at, se.updated_at, se.deleted_at, se.final_grade,
       e.student_id
FROM section_enrollments se
JOIN enrollments e ON e.id = se.enrollment_id
WHERE se.section_id = $1::uuid
  AND se.deleted_at IS NULL
  AND ($2::uuid IS NULL OR se.id < $2::uuid)
  AND EXISTS (
    SELECT 1 FROM section_teachers st
    WHERE st.section_id = $1::uuid AND st.teacher_id = $3::uuid
  )
ORDER BY se.id DESC
LIMIT $4::int
`

type ListSectionRosterForTeacherParams struct {
	SectionID pgtype.UUID
	PageToken pgtype.UUID
	TeacherID pgtype.UUID
	RowLimit  int32
}

type ListSectionRosterForTeacherRow struct {
	ID           pgtype.UUID
	EnrollmentID pgtype.UUID
	SectionID    pgtype.UUID
	Status       string
	RegisteredAt pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	FinalGrade   pgtype.Numeric
	StudentID    pgtype.UUID
}

// Returns live section_enrollment rows for a section the caller teaches, with student_id
// projected from the linked enrollment.
// EXISTS guard: if the caller is not in section_teachers for the section, returns no rows
// (anti-leak: existence is never disclosed — empty page, not PermissionDenied).
// Includes withdrawn enrollments (status distinguishes them from active ones).
// Keyset pagination on se.id DESC; page_token is the exclusive upper bound.
// Cross-domain read: reads section_teachers (catalog schema) and enrollments.
// This is the same intra-DB coupling already established in this context (see file header).
func (q *Queries) ListSectionRosterForTeacher(ctx context.Context, arg ListSectionRosterForTeacherParams) ([]ListSectionRosterForTeacherRow, error) {
	rows, err := q.db.Query(ctx, listSectionRosterForTeacher,
		arg.SectionID,
		arg.PageToken,
		arg.TeacherID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSectionRosterForTeacherRow
	for rows.Next() {
		var i ListSectionRosterForTeacherRow
		if err := rows.Scan(
			&i.ID,
			&i.EnrollmentID,
			&i.SectionID,
			&i.Status,
			&i.RegisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FinalGrade,
			&i.StudentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionRosterForTeacherAll = `-- name: ListSectionRosterForTeacherAll :many
SELECT se.id, se.enrollment_id, se.section_id, se.status, se.registered_at,
       se.created_at, se.updated_at, se.deleted_at, se.final_grade,
       e.student_id
FROM section_enrollments se
JOIN enrollments e ON e.id = se.enrollment_id
WHERE se.section_id = $1::uuid
  AND se.deleted_at IS NULL
  AND ($2::uuid IS NULL OR se.id < $2::uuid)
ORDER BY se.id DESC
LIMIT $3::int
`

type ListSectionRosterForTeacherAllParams struct {
	SectionID pgtype.UUID
	PageToken pgtype.UUID
	RowLimit  int32
}

type ListSectionRosterForTeacherAllRow struct {
	ID           pgtype.UUID
	EnrollmentID pgtype.UUID
	SectionID    pgtype.UUID
	Status       string
	RegisteredAt pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	FinalGrade   pgtype.Numeric
	StudentID    pgtype.UUID
}

// Returns live section_enrollment rows for a section WITHOUT the section_teachers EXISTS
// guard. Used by the admin bypass so callers holding enrollment.manage can see the full
// roster regardless of whether they are assigned as a teacher.
// Includes withdrawn enrollments (status distinguishes them from active ones).
// Keyset pagination on se.id DESC; page_token is the exclusive upper bound.
// Cross-domain read: reads enrollments table — same intra-DB coupling as the teacher variant.
func (q *Queries) ListSectionRosterForTeacherAll(ctx context.Context, arg ListSectionRosterForTeacherAllParams) ([]ListSectionRosterForTeacherAllRow, error) {
	rows, err := q.db.Query(ctx, listSectionRosterForTeacherAll, arg.SectionID, arg.PageToken, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSectionRosterForTeacherAllRow
	for rows.Next() {
		var i ListSectionRosterForTeacherAllRow
		if err := rows.Scan(
			&i.ID,
			&i.EnrollmentID,
			&i.SectionID,
			&i.Status,
			&i.RegisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FinalGrade,
			&i.StudentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveEnrollmentByID = `-- name: ResolveEnrollmentByID :one
SELECT e.id, e.student_id, e.program_id, e.year, e.status, e.deleted_at
FROM enrollments e
WHERE e.id = $1
  AND e.deleted_at IS NULL
`

type ResolveEnrollmentByIDRow struct {
	ID        pgtype.UUID
	StudentID pgtype.UUID
	ProgramID pgtype.UUID
	Year      int32
	Status    string
	DeletedAt pgtype.Timestamptz
}

// Resolves an enrollment by id without filtering on status.
// Returns year, status, and deleted_at so the caller can distinguish:
//
//	not found / soft-deleted → ErrNotFound
//	found but status != 'paid' → ErrNotPaid
//	found but year ≠ section period year → ErrEnrollmentYearMismatch
func (q *Queries) ResolveEnrollmentByID(ctx context.Context, id pgtype.UUID) (ResolveEnrollmentByIDRow, error) {
	row := q.db.QueryRow(ctx, resolveEnrollmentByID, id)
	var i ResolveEnrollmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ProgramID,
		&i.Year,
		&i.Status,
		&i.DeletedAt,
	)
	return i, err
}

const resolveEnrollmentByStudentAndProgram = `-- name: ResolveEnrollmentByStudentAndProgram :one
SELECT e.id, e.student_id, e.program_id, e.status, e.deleted_at
FROM enrollments e
WHERE e.student_id = $1
  AND e.program_id = $2
  AND e.year = $3
  AND e.deleted_at IS NULL
`

type ResolveEnrollmentByStudentAndProgramParams struct {
	StudentID pgtype.UUID
	ProgramID pgtype.UUID
	Year      int32
}

type ResolveEnrollmentByStudentAndProgramRow struct {
	ID        pgtype.UUID
	StudentID pgtype.UUID
	ProgramID pgtype.UUID
	Status    string
	DeletedAt pgtype.Timestamptz
}

// Resolves an enrollment for a student in a specific program and year.
// Returns the full status and deleted_at so the caller can distinguish:
//
//	not found / soft-deleted → ErrNotFound
//	found but status != 'paid' → ErrNotPaid
//
// The year parameter must equal the section's academic period year so that a
// matrícula from a different year cannot satisfy a section in another year.
func (q *Queries) ResolveEnrollmentByStudentAndProgram(ctx context.Context, arg ResolveEnrollmentByStudentAndProgramParams) (ResolveEnrollmentByStudentAndProgramRow, error) {
	row := q.db.QueryRow(ctx, resolveEnrollmentByStudentAndProgram, arg.StudentID, arg.ProgramID, arg.Year)
	var i ResolveEnrollmentByStudentAndProgramRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ProgramID,
		&i.Status,
		&i.DeletedAt,
	)
	return i, err
}

const reviveSectionEnrollment = `-- name: ReviveSectionEnrollment :one
UPDATE section_enrollments
SET status     = 'in_progress',
    deleted_at = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, enrollment_id, section_id, status, registered_at, created_at, updated_at, deleted_at, final_grade
`

// Revives a withdrawn inscription: sets status back to in_progress and clears deleted_at.
func (q *Queries) ReviveSectionEnrollment(ctx context.Context, id pgtype.UUID) (SectionEnrollment, error) {
	row := q.db.QueryRow(ctx, reviveSectionEnrollment, id)
	var i SectionEnrollment
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.SectionID,
		&i.Status,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FinalGrade,
	)
	return i, err
}

const setSectionEnrollmentOutcome = `-- name: SetSectionEnrollmentOutcome :one
UPDATE section_enrollments
SET status      = $2,
    final_grade = $3,
    updated_at  = now()
WHERE id = $1
  AND deleted_at IS NULL
  AND status IN ('in_progress', 'passed', 'failed')
  AND $2 IN ('passed', 'failed')
RETURNING id, enrollment_id, section_id, status, registered_at, created_at, updated_at, deleted_at, final_grade
`

type SetSectionEnrollmentOutcomeParams struct {
	ID         pgtype.UUID
	Status     string
	FinalGrade pgtype.Numeric
}

// Transitions a section_enrollment status to passed or failed and writes the
// computed final grade, within a caller-owned transaction.
// Source states in_progress/passed/failed are all valid (allows passed<->failed flips).
// withdrawn source is rejected (0 rows returned — treated as ErrInvalidTransition).
// Target must be passed or failed; in_progress is not a valid target.
func (q *Queries) SetSectionEnrollmentOutcome(ctx context.Context, arg SetSectionEnrollmentOutcomeParams) (SectionEnrollment, error) {
	row := q.db.QueryRow(ctx, setSectionEnrollmentOutcome, arg.ID, arg.Status, arg.FinalGrade)
	var i SectionEnrollment
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.SectionID,
		&i.Status,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FinalGrade,
	)
	return i, err
}

const withdrawSectionEnrollment = `-- name: WithdrawSectionEnrollment :one
UPDATE section_enrollments
SET status     = 'withdrawn',
    updated_at = now()
WHERE id = $1 AND status = 'in_progress' AND deleted_at IS NULL
RETURNING id, enrollment_id, section_id, status, registered_at, created_at, updated_at, deleted_at, final_grade
`

// Transitions an in_progress inscription to withdrawn.
// Sets updated_at; does NOT set deleted_at — withdrawn rows are retained for audit/revival.
func (q *Queries) WithdrawSectionEnrollment(ctx context.Context, id pgtype.UUID) (SectionEnrollment, error) {
	row := q.db.QueryRow(ctx, withdrawSectionEnrollment, id)
	var i SectionEnrollment
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.SectionID,
		&i.Status,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FinalGrade,
	)
	return i, err
}
