// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package section_enrollmentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Non-locking snapshot count of active inscriptions for pre-check fast-fail.
	// Uses the partial index section_enrollments_active_seat_idx.
	// NOT authoritative — the under-lock count is the source of truth.
	CountActiveSeats(ctx context.Context, sectionID pgtype.UUID) (int64, error)
	// Checks whether a course belongs to a program's course list.
	// Returns a boolean; false (no row) means the course is not in the program.
	CourseInProgram(ctx context.Context, arg CourseInProgramParams) (bool, error)
	// Cross-domain read strategy: queries here read enrollment, sections, academic_periods,
	// and program_courses schema directly. Coupling is to the shared migration schema, not
	// to Go service layers. The single transaction boundary is what makes paid+program+seat
	// checks atomic. This is the canonical approach for this codebase.
	// Non-locking read of section capacity and course_id.
	// Used for the pre-check fast-fail BEFORE BeginTx; avoids acquiring the row lock
	// for sections that are obviously full or missing. Returns ErrNoRows when absent.
	GetSectionCapacity(ctx context.Context, id pgtype.UUID) (GetSectionCapacityRow, error)
	GetSectionEnrollmentByID(ctx context.Context, id pgtype.UUID) (SectionEnrollment, error)
	// Fetches a LIVE inscription row for (enrollment_id, section_id) with a FOR UPDATE lock
	// for revival detection. Filters deleted_at IS NULL so that a soft-deleted row never
	// triggers AlreadyExists or revival logic. Lock order: acquired after section lock.
	GetSectionEnrollmentByKeyForUpdate(ctx context.Context, arg GetSectionEnrollmentByKeyForUpdateParams) (SectionEnrollment, error)
	// Locks the section row FOR UPDATE and fetches capacity, course_id, period_year, and
	// whether now() falls within the academic period's enrollment window (inclusive on both ends).
	// window_open=false when the window is not configured (fail-closed).
	// period_year is used by the caller to enforce that the linked enrollment matches
	// the section's academic year before inserting.
	// Used as lock step #1 in EnrollSectionTx; lock order is section → key row.
	GetSectionForUpdateWithWindow(ctx context.Context, id pgtype.UUID) (GetSectionForUpdateWithWindowRow, error)
	InsertSectionEnrollment(ctx context.Context, arg InsertSectionEnrollmentParams) (SectionEnrollment, error)
	// Returns all live inscriptions for a student by joining enrollments on student_id.
	ListOwnSectionEnrollments(ctx context.Context, studentID pgtype.UUID) ([]SectionEnrollment, error)
	ListSectionEnrollments(ctx context.Context, arg ListSectionEnrollmentsParams) ([]SectionEnrollment, error)
	// Resolves an enrollment by id without filtering on status.
	// Returns year, status, and deleted_at so the caller can distinguish:
	//   not found / soft-deleted → ErrNotFound
	//   found but status != 'paid' → ErrNotPaid
	//   found but year ≠ section period year → ErrEnrollmentYearMismatch
	ResolveEnrollmentByID(ctx context.Context, id pgtype.UUID) (ResolveEnrollmentByIDRow, error)
	// Resolves an enrollment for a student in a specific program and year.
	// Returns the full status and deleted_at so the caller can distinguish:
	//   not found / soft-deleted → ErrNotFound
	//   found but status != 'paid' → ErrNotPaid
	// The year parameter must equal the section's academic period year so that a
	// matrícula from a different year cannot satisfy a section in another year.
	ResolveEnrollmentByStudentAndProgram(ctx context.Context, arg ResolveEnrollmentByStudentAndProgramParams) (ResolveEnrollmentByStudentAndProgramRow, error)
	// Revives a withdrawn inscription: sets status back to in_progress and clears deleted_at.
	ReviveSectionEnrollment(ctx context.Context, id pgtype.UUID) (SectionEnrollment, error)
	// Transitions a section_enrollment status to passed or failed and writes the
	// computed final grade, within a caller-owned transaction.
	// Source states in_progress/passed/failed are all valid (allows passed<->failed flips).
	// withdrawn source is rejected (0 rows returned — treated as ErrInvalidTransition).
	// Target must be passed or failed; in_progress is not a valid target.
	SetSectionEnrollmentOutcome(ctx context.Context, arg SetSectionEnrollmentOutcomeParams) (SectionEnrollment, error)
	// Transitions an in_progress inscription to withdrawn.
	// Sets updated_at; does NOT set deleted_at — withdrawn rows are retained for audit/revival.
	WithdrawSectionEnrollment(ctx context.Context, id pgtype.UUID) (SectionEnrollment, error)
}

var _ Querier = (*Queries)(nil)
