// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package section_enrollmentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSeats = `-- name: CountActiveSeats :one
SELECT count(*)
FROM section_enrollments
WHERE section_id = $1
  AND status <> 'withdrawn'
  AND deleted_at IS NULL
`

// Non-locking snapshot count of active inscriptions for pre-check fast-fail.
// Uses the partial index section_enrollments_active_seat_idx.
// NOT authoritative — the under-lock count is the source of truth.
func (q *Queries) CountActiveSeats(ctx context.Context, sectionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSeats, sectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const courseInProgram = `-- name: CourseInProgram :one
SELECT EXISTS(
    SELECT 1 FROM program_courses
    WHERE program_id = $1 AND course_id = $2
) AS exists
`

type CourseInProgramParams struct {
	ProgramID pgtype.UUID
	CourseID  pgtype.UUID
}

// Checks whether a course belongs to a program's course list.
// Returns a boolean; false (no row) means the course is not in the program.
func (q *Queries) CourseInProgram(ctx context.Context, arg CourseInProgramParams) (bool, error) {
	row := q.db.QueryRow(ctx, courseInProgram, arg.ProgramID, arg.CourseID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getSectionCapacity = `-- name: GetSectionCapacity :one

SELECT
    s.capacity,
    s.course_id
FROM sections s
WHERE s.id = $1 AND s.deleted_at IS NULL
`

type GetSectionCapacityRow struct {
	Capacity int32
	CourseID pgtype.UUID
}

// Cross-domain read strategy: queries here read enrollment, sections, academic_periods,
// and program_courses schema directly. Coupling is to the shared migration schema, not
// to Go service layers. The single transaction boundary is what makes paid+program+seat
// checks atomic. This is the canonical approach for this codebase.
// Non-locking read of section capacity and course_id.
// Used for the pre-check fast-fail BEFORE BeginTx; avoids acquiring the row lock
// for sections that are obviously full or missing. Returns ErrNoRows when absent.
func (q *Queries) GetSectionCapacity(ctx context.Context, id pgtype.UUID) (GetSectionCapacityRow, error) {
	row := q.db.QueryRow(ctx, getSectionCapacity, id)
	var i GetSectionCapacityRow
	err := row.Scan(&i.Capacity, &i.CourseID)
	return i, err
}

const getSectionEnrollmentByID = `-- name: GetSectionEnrollmentByID :one
SELECT id, enrollment_id, section_id, status, registered_at, created_at, updated_at, deleted_at, final_grade FROM section_enrollments
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSectionEnrollmentByID(ctx context.Context, id pgtype.UUID) (SectionEnrollment, error) {
	row := q.db.QueryRow(ctx, getSectionEnrollmentByID, id)
	var i SectionEnrollment
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.SectionID,
		&i.Status,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FinalGrade,
	)
	return i, err
}

const getSectionEnrollmentByKeyForUpdate = `-- name: GetSectionEnrollmentByKeyForUpdate :one
SELECT id, enrollment_id, section_id, status, registered_at, created_at, updated_at, deleted_at, final_grade FROM section_enrollments
WHERE enrollment_id = $1 AND section_id = $2 AND deleted_at IS NULL
FOR UPDATE
`

type GetSectionEnrollmentByKeyForUpdateParams struct {
	EnrollmentID pgtype.UUID
	SectionID    pgtype.UUID
}

// Fetches a LIVE inscription row for (enrollment_id, section_id) with a FOR UPDATE lock
// for revival detection. Filters deleted_at IS NULL so that a soft-deleted row never
// triggers AlreadyExists or revival logic. Lock order: acquired after section lock.
func (q *Queries) GetSectionEnrollmentByKeyForUpdate(ctx context.Context, arg GetSectionEnrollmentByKeyForUpdateParams) (SectionEnrollment, error) {
	row := q.db.QueryRow(ctx, getSectionEnrollmentByKeyForUpdate, arg.EnrollmentID, arg.SectionID)
	var i SectionEnrollment
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.SectionID,
		&i.Status,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FinalGrade,
	)
	return i, err
}

const getSectionForUpdateWithWindow = `-- name: GetSectionForUpdateWithWindow :one
SELECT
    s.capacity,
    s.course_id,
    ap.year AS period_year,
    (
        ap.enrollment_starts_at IS NOT NULL
        AND ap.enrollment_ends_at IS NOT NULL
        AND now() BETWEEN ap.enrollment_starts_at AND ap.enrollment_ends_at
    ) AS window_open
FROM sections s
JOIN academic_periods ap ON ap.id = s.academic_period_id
WHERE s.id = $1 AND s.deleted_at IS NULL
FOR UPDATE OF s
`

type GetSectionForUpdateWithWindowRow struct {
	Capacity   int32
	CourseID   pgtype.UUID
	PeriodYear int32
	WindowOpen pgtype.Bool
}

// Locks the section row FOR UPDATE and fetches capacity, course_id, period_year, and
// whether now() falls within the academic period's enrollment window (inclusive on both ends).
// window_open=false when the window is not configured (fail-closed).
// period_year is used by the caller to enforce that the linked enrollment matches
// the section's academic year before inserting.
// Used as lock step #1 in EnrollSectionTx; lock order is section → key row.
func (q *Queries) GetSectionForUpdateWithWindow(ctx context.Context, id pgtype.UUID) (GetSectionForUpdateWithWindowRow, error) {
	row := q.db.QueryRow(ctx, getSectionForUpdateWithWindow, id)
	var i GetSectionForUpdateWithWindowRow
	err := row.Scan(
		&i.Capacity,
		&i.CourseID,
		&i.PeriodYear,
		&i.WindowOpen,
	)
	return i, err
}

const insertSectionEnrollment = `-- name: InsertSectionEnrollment :one
INSERT INTO section_enrollments (enrollment_id, section_id, status)
VALUES ($1, $2, 'in_progress')
RETURNING id, enrollment_id, section_id, status, registered_at, created_at, updated_at, deleted_at, final_grade
`

type InsertSectionEnrollmentParams struct {
	EnrollmentID pgtype.UUID
	SectionID    pgtype.UUID
}

func (q *Queries) InsertSectionEnrollment(ctx context.Context, arg InsertSectionEnrollmentParams) (SectionEnrollment, error) {
	row := q.db.QueryRow(ctx, insertSectionEnrollment, arg.EnrollmentID, arg.SectionID)
	var i SectionEnrollment
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.SectionID,
		&i.Status,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FinalGrade,
	)
	return i, err
}

const listOwnSectionEnrollments = `-- name: ListOwnSectionEnrollments :many
SELECT se.id, se.enrollment_id, se.section_id, se.status, se.registered_at, se.created_at, se.updated_at, se.deleted_at, se.final_grade
FROM section_enrollments se
JOIN enrollments e ON e.id = se.enrollment_id
WHERE e.student_id = $1
  AND se.deleted_at IS NULL
ORDER BY se.created_at
`

// Returns all live inscriptions for a student by joining enrollments on student_id.
func (q *Queries) ListOwnSectionEnrollments(ctx context.Context, studentID pgtype.UUID) ([]SectionEnrollment, error) {
	rows, err := q.db.Query(ctx, listOwnSectionEnrollments, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SectionEnrollment
	for rows.Next() {
		var i SectionEnrollment
		if err := rows.Scan(
			&i.ID,
			&i.EnrollmentID,
			&i.SectionID,
			&i.Status,
			&i.RegisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FinalGrade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionEnrollments = `-- name: ListSectionEnrollments :many
SELECT id, enrollment_id, section_id, status, registered_at, created_at, updated_at, deleted_at, final_grade FROM section_enrollments
WHERE deleted_at IS NULL
  AND ($1::uuid IS NULL   OR section_id   = $1::uuid)
  AND ($2::uuid IS NULL OR enrollment_id = $2::uuid)
  AND ($3::text IS NULL        OR status        = $3::text)
ORDER BY created_at
`

type ListSectionEnrollmentsParams struct {
	SectionID    pgtype.UUID
	EnrollmentID pgtype.UUID
	Status       pgtype.Text
}

func (q *Queries) ListSectionEnrollments(ctx context.Context, arg ListSectionEnrollmentsParams) ([]SectionEnrollment, error) {
	rows, err := q.db.Query(ctx, listSectionEnrollments, arg.SectionID, arg.EnrollmentID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SectionEnrollment
	for rows.Next() {
		var i SectionEnrollment
		if err := rows.Scan(
			&i.ID,
			&i.EnrollmentID,
			&i.SectionID,
			&i.Status,
			&i.RegisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FinalGrade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveEnrollmentByID = `-- name: ResolveEnrollmentByID :one
SELECT e.id, e.student_id, e.program_id, e.year, e.status, e.deleted_at
FROM enrollments e
WHERE e.id = $1
  AND e.deleted_at IS NULL
`

type ResolveEnrollmentByIDRow struct {
	ID        pgtype.UUID
	StudentID pgtype.UUID
	ProgramID pgtype.UUID
	Year      int32
	Status    string
	DeletedAt pgtype.Timestamptz
}

// Resolves an enrollment by id without filtering on status.
// Returns year, status, and deleted_at so the caller can distinguish:
//
//	not found / soft-deleted → ErrNotFound
//	found but status != 'paid' → ErrNotPaid
//	found but year ≠ section period year → ErrEnrollmentYearMismatch
func (q *Queries) ResolveEnrollmentByID(ctx context.Context, id pgtype.UUID) (ResolveEnrollmentByIDRow, error) {
	row := q.db.QueryRow(ctx, resolveEnrollmentByID, id)
	var i ResolveEnrollmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ProgramID,
		&i.Year,
		&i.Status,
		&i.DeletedAt,
	)
	return i, err
}

const resolveEnrollmentByStudentAndProgram = `-- name: ResolveEnrollmentByStudentAndProgram :one
SELECT e.id, e.student_id, e.program_id, e.status, e.deleted_at
FROM enrollments e
WHERE e.student_id = $1
  AND e.program_id = $2
  AND e.year = $3
  AND e.deleted_at IS NULL
`

type ResolveEnrollmentByStudentAndProgramParams struct {
	StudentID pgtype.UUID
	ProgramID pgtype.UUID
	Year      int32
}

type ResolveEnrollmentByStudentAndProgramRow struct {
	ID        pgtype.UUID
	StudentID pgtype.UUID
	ProgramID pgtype.UUID
	Status    string
	DeletedAt pgtype.Timestamptz
}

// Resolves an enrollment for a student in a specific program and year.
// Returns the full status and deleted_at so the caller can distinguish:
//
//	not found / soft-deleted → ErrNotFound
//	found but status != 'paid' → ErrNotPaid
//
// The year parameter must equal the section's academic period year so that a
// matrícula from a different year cannot satisfy a section in another year.
func (q *Queries) ResolveEnrollmentByStudentAndProgram(ctx context.Context, arg ResolveEnrollmentByStudentAndProgramParams) (ResolveEnrollmentByStudentAndProgramRow, error) {
	row := q.db.QueryRow(ctx, resolveEnrollmentByStudentAndProgram, arg.StudentID, arg.ProgramID, arg.Year)
	var i ResolveEnrollmentByStudentAndProgramRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ProgramID,
		&i.Status,
		&i.DeletedAt,
	)
	return i, err
}

const reviveSectionEnrollment = `-- name: ReviveSectionEnrollment :one
UPDATE section_enrollments
SET status     = 'in_progress',
    deleted_at = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, enrollment_id, section_id, status, registered_at, created_at, updated_at, deleted_at, final_grade
`

// Revives a withdrawn inscription: sets status back to in_progress and clears deleted_at.
func (q *Queries) ReviveSectionEnrollment(ctx context.Context, id pgtype.UUID) (SectionEnrollment, error) {
	row := q.db.QueryRow(ctx, reviveSectionEnrollment, id)
	var i SectionEnrollment
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.SectionID,
		&i.Status,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FinalGrade,
	)
	return i, err
}

const setSectionEnrollmentOutcome = `-- name: SetSectionEnrollmentOutcome :one
UPDATE section_enrollments
SET status      = $2,
    final_grade = $3,
    updated_at  = now()
WHERE id = $1
  AND deleted_at IS NULL
  AND status IN ('in_progress', 'passed', 'failed')
  AND $2 IN ('passed', 'failed')
RETURNING id, enrollment_id, section_id, status, registered_at, created_at, updated_at, deleted_at, final_grade
`

type SetSectionEnrollmentOutcomeParams struct {
	ID         pgtype.UUID
	Status     string
	FinalGrade pgtype.Numeric
}

// Transitions a section_enrollment status to passed or failed and writes the
// computed final grade, within a caller-owned transaction.
// Source states in_progress/passed/failed are all valid (allows passed<->failed flips).
// withdrawn source is rejected (0 rows returned — treated as ErrInvalidTransition).
// Target must be passed or failed; in_progress is not a valid target.
func (q *Queries) SetSectionEnrollmentOutcome(ctx context.Context, arg SetSectionEnrollmentOutcomeParams) (SectionEnrollment, error) {
	row := q.db.QueryRow(ctx, setSectionEnrollmentOutcome, arg.ID, arg.Status, arg.FinalGrade)
	var i SectionEnrollment
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.SectionID,
		&i.Status,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FinalGrade,
	)
	return i, err
}

const withdrawSectionEnrollment = `-- name: WithdrawSectionEnrollment :one
UPDATE section_enrollments
SET status     = 'withdrawn',
    updated_at = now()
WHERE id = $1 AND status = 'in_progress' AND deleted_at IS NULL
RETURNING id, enrollment_id, section_id, status, registered_at, created_at, updated_at, deleted_at, final_grade
`

// Transitions an in_progress inscription to withdrawn.
// Sets updated_at; does NOT set deleted_at — withdrawn rows are retained for audit/revival.
func (q *Queries) WithdrawSectionEnrollment(ctx context.Context, id pgtype.UUID) (SectionEnrollment, error) {
	row := q.db.QueryRow(ctx, withdrawSectionEnrollment, id)
	var i SectionEnrollment
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.SectionID,
		&i.Status,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FinalGrade,
	)
	return i, err
}
