// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package reportsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActaForSectionAdmin(ctx context.Context, id pgtype.UUID) ([]ActaForSectionAdminRow, error)
	ActaForSectionByTeacher(ctx context.Context, arg ActaForSectionByTeacherParams) ([]ActaForSectionByTeacherRow, error)
	// Cross-domain read queries — coupled to the shared migration schema, not to any Go domain package.
	// All queries filter deleted_at IS NULL on every soft-deletable table.
	// LIMIT cap+1 pattern: service detects len(rows) > cap and sets truncated=true.
	ActaSectionExists(ctx context.Context, id pgtype.UUID) (bool, error)
	FichaForStudent(ctx context.Context, studentID pgtype.UUID) ([]FichaForStudentRow, error)
	OccupancyForPeriod(ctx context.Context, academicPeriodID pgtype.UUID) ([]OccupancyForPeriodRow, error)
	OccupancyPeriodExists(ctx context.Context, id pgtype.UUID) (bool, error)
	ProgramExists(ctx context.Context, id pgtype.UUID) (bool, error)
	ProgramSummary(ctx context.Context, arg ProgramSummaryParams) ([]ProgramSummaryRow, error)
	StudentExists(ctx context.Context, userID pgtype.UUID) (bool, error)
}

var _ Querier = (*Queries)(nil)
