// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package reportsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const actaForSectionAdmin = `-- name: ActaForSectionAdmin :many
SELECT
    se.id                       AS se_id,
    e.student_id                AS student_id,
    up.given_names              AS given_names,
    up.last_name_paternal       AS last_name_paternal,
    up.last_name_maternal       AS last_name_maternal,
    ev.id                       AS evaluation_id,
    ev.position                 AS position,
    g.value                     AS grade_value,
    se.final_grade              AS final_grade,
    se.status                   AS enrollment_status
FROM sections s
JOIN section_enrollments se
    ON se.section_id = s.id
    AND se.status != 'withdrawn'
    AND se.deleted_at IS NULL
JOIN enrollments e
    ON e.id = se.enrollment_id
    AND e.deleted_at IS NULL
JOIN student_profiles sp
    ON sp.user_id = e.student_id
    AND sp.deleted_at IS NULL
JOIN user_profiles up
    ON up.user_id = e.student_id
    AND up.deleted_at IS NULL
LEFT JOIN grades g
    ON g.section_enrollment_id = se.id
    AND g.deleted_at IS NULL
LEFT JOIN evaluations ev
    ON ev.id = g.evaluation_id
    AND ev.deleted_at IS NULL
WHERE s.id = $1
  AND s.deleted_at IS NULL
ORDER BY up.last_name_paternal, up.given_names, ev.position
LIMIT 501
`

type ActaForSectionAdminRow struct {
	SeID             pgtype.UUID
	StudentID        pgtype.UUID
	GivenNames       string
	LastNamePaternal string
	LastNameMaternal pgtype.Text
	EvaluationID     pgtype.UUID
	Position         pgtype.Int4
	GradeValue       pgtype.Numeric
	FinalGrade       pgtype.Numeric
	EnrollmentStatus string
}

func (q *Queries) ActaForSectionAdmin(ctx context.Context, id pgtype.UUID) ([]ActaForSectionAdminRow, error) {
	rows, err := q.db.Query(ctx, actaForSectionAdmin, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActaForSectionAdminRow
	for rows.Next() {
		var i ActaForSectionAdminRow
		if err := rows.Scan(
			&i.SeID,
			&i.StudentID,
			&i.GivenNames,
			&i.LastNamePaternal,
			&i.LastNameMaternal,
			&i.EvaluationID,
			&i.Position,
			&i.GradeValue,
			&i.FinalGrade,
			&i.EnrollmentStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actaForSectionByTeacher = `-- name: ActaForSectionByTeacher :many
SELECT
    se.id                       AS se_id,
    e.student_id                AS student_id,
    up.given_names              AS given_names,
    up.last_name_paternal       AS last_name_paternal,
    up.last_name_maternal       AS last_name_maternal,
    ev.id                       AS evaluation_id,
    ev.position                 AS position,
    g.value                     AS grade_value,
    se.final_grade              AS final_grade,
    se.status                   AS enrollment_status
FROM sections s
JOIN section_enrollments se
    ON se.section_id = s.id
    AND se.status != 'withdrawn'
    AND se.deleted_at IS NULL
JOIN enrollments e
    ON e.id = se.enrollment_id
    AND e.deleted_at IS NULL
JOIN student_profiles sp
    ON sp.user_id = e.student_id
    AND sp.deleted_at IS NULL
JOIN user_profiles up
    ON up.user_id = e.student_id
    AND up.deleted_at IS NULL
LEFT JOIN grades g
    ON g.section_enrollment_id = se.id
    AND g.deleted_at IS NULL
LEFT JOIN evaluations ev
    ON ev.id = g.evaluation_id
    AND ev.deleted_at IS NULL
WHERE s.id = $1
  AND s.deleted_at IS NULL
  AND EXISTS (
      SELECT 1 FROM section_teachers st
      WHERE st.section_id = s.id AND st.teacher_id = $2
  )
ORDER BY up.last_name_paternal, up.given_names, ev.position
LIMIT 501
`

type ActaForSectionByTeacherParams struct {
	ID        pgtype.UUID
	TeacherID pgtype.UUID
}

type ActaForSectionByTeacherRow struct {
	SeID             pgtype.UUID
	StudentID        pgtype.UUID
	GivenNames       string
	LastNamePaternal string
	LastNameMaternal pgtype.Text
	EvaluationID     pgtype.UUID
	Position         pgtype.Int4
	GradeValue       pgtype.Numeric
	FinalGrade       pgtype.Numeric
	EnrollmentStatus string
}

func (q *Queries) ActaForSectionByTeacher(ctx context.Context, arg ActaForSectionByTeacherParams) ([]ActaForSectionByTeacherRow, error) {
	rows, err := q.db.Query(ctx, actaForSectionByTeacher, arg.ID, arg.TeacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActaForSectionByTeacherRow
	for rows.Next() {
		var i ActaForSectionByTeacherRow
		if err := rows.Scan(
			&i.SeID,
			&i.StudentID,
			&i.GivenNames,
			&i.LastNamePaternal,
			&i.LastNameMaternal,
			&i.EvaluationID,
			&i.Position,
			&i.GradeValue,
			&i.FinalGrade,
			&i.EnrollmentStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actaSectionExists = `-- name: ActaSectionExists :one

SELECT EXISTS(
    SELECT 1 FROM sections WHERE id = $1 AND deleted_at IS NULL
) AS exists
`

// Cross-domain read queries — coupled to the shared migration schema, not to any Go domain package.
// All queries filter deleted_at IS NULL on every soft-deletable table.
// LIMIT cap+1 pattern: service detects len(rows) > cap and sets truncated=true.
func (q *Queries) ActaSectionExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, actaSectionExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const fichaForStudent = `-- name: FichaForStudent :many
SELECT
    ap.id                                                           AS academic_period_id,
    (ap.year::text || '-' || ap.term::text)::text                  AS academic_period_name,
    s.id                                                            AS section_id,
    c.name                                                          AS course_name,
    se.status                                                       AS enrollment_status,
    se.final_grade                                                  AS final_grade,
    ev.id                                                           AS evaluation_id,
    ev.position                                                     AS position,
    g.value                                                         AS grade_value,
    (up.given_names || ' ' || up.last_name_paternal)::text         AS student_name
FROM enrollments e
JOIN section_enrollments se
    ON se.enrollment_id = e.id
    AND se.deleted_at IS NULL
JOIN sections s
    ON s.id = se.section_id
    AND s.deleted_at IS NULL
JOIN courses c
    ON c.id = s.course_id
JOIN academic_periods ap
    ON ap.id = s.academic_period_id
JOIN user_profiles up
    ON up.user_id = e.student_id
    AND up.deleted_at IS NULL
LEFT JOIN grades g
    ON g.section_enrollment_id = se.id
    AND g.deleted_at IS NULL
LEFT JOIN evaluations ev
    ON ev.id = g.evaluation_id
    AND ev.deleted_at IS NULL
WHERE e.student_id = $1
  AND e.deleted_at IS NULL
ORDER BY ap.year, ap.term, c.code, ev.position
LIMIT 1001
`

type FichaForStudentRow struct {
	AcademicPeriodID   pgtype.UUID
	AcademicPeriodName string
	SectionID          pgtype.UUID
	CourseName         string
	EnrollmentStatus   string
	FinalGrade         pgtype.Numeric
	EvaluationID       pgtype.UUID
	Position           pgtype.Int4
	GradeValue         pgtype.Numeric
	StudentName        string
}

func (q *Queries) FichaForStudent(ctx context.Context, studentID pgtype.UUID) ([]FichaForStudentRow, error) {
	rows, err := q.db.Query(ctx, fichaForStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FichaForStudentRow
	for rows.Next() {
		var i FichaForStudentRow
		if err := rows.Scan(
			&i.AcademicPeriodID,
			&i.AcademicPeriodName,
			&i.SectionID,
			&i.CourseName,
			&i.EnrollmentStatus,
			&i.FinalGrade,
			&i.EvaluationID,
			&i.Position,
			&i.GradeValue,
			&i.StudentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isTeacherForSection = `-- name: IsTeacherForSection :one
SELECT EXISTS(
    SELECT 1 FROM section_teachers
    WHERE section_id = $1 AND teacher_id = $2
) AS is_member
`

type IsTeacherForSectionParams struct {
	SectionID pgtype.UUID
	TeacherID pgtype.UUID
}

// Returns true when teacher_id appears in section_teachers for the given section_id.
// Used to gate teacher access BEFORE the cache lookup (anti-leak: caller never learns
// whether the section exists independently of the membership result).
func (q *Queries) IsTeacherForSection(ctx context.Context, arg IsTeacherForSectionParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTeacherForSection, arg.SectionID, arg.TeacherID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const occupancyForPeriod = `-- name: OccupancyForPeriod :many
SELECT
    s.id                                            AS section_id,
    s.capacity                                      AS capacity,
    c.name                                          AS course_name,
    COUNT(se.id)                                    AS active_seat_count,
    (ap.year::text || '-' || ap.term::text)::text   AS academic_period_name
FROM sections s
JOIN academic_periods ap
    ON ap.id = s.academic_period_id
LEFT JOIN section_enrollments se
    ON se.section_id = s.id
    AND se.status != 'withdrawn'
    AND se.deleted_at IS NULL
LEFT JOIN courses c
    ON c.id = s.course_id
WHERE s.academic_period_id = $1
  AND s.deleted_at IS NULL
GROUP BY s.id, s.capacity, c.name, ap.year, ap.term
ORDER BY s.id
LIMIT 1001
`

type OccupancyForPeriodRow struct {
	SectionID          pgtype.UUID
	Capacity           int32
	CourseName         pgtype.Text
	ActiveSeatCount    int64
	AcademicPeriodName string
}

func (q *Queries) OccupancyForPeriod(ctx context.Context, academicPeriodID pgtype.UUID) ([]OccupancyForPeriodRow, error) {
	rows, err := q.db.Query(ctx, occupancyForPeriod, academicPeriodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OccupancyForPeriodRow
	for rows.Next() {
		var i OccupancyForPeriodRow
		if err := rows.Scan(
			&i.SectionID,
			&i.Capacity,
			&i.CourseName,
			&i.ActiveSeatCount,
			&i.AcademicPeriodName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const occupancyPeriodExists = `-- name: OccupancyPeriodExists :one
SELECT EXISTS(
    SELECT 1 FROM academic_periods WHERE id = $1 AND deleted_at IS NULL
) AS exists
`

func (q *Queries) OccupancyPeriodExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, occupancyPeriodExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const programExists = `-- name: ProgramExists :one
SELECT EXISTS(
    SELECT 1 FROM programs WHERE id = $1 AND deleted_at IS NULL
) AS exists
`

func (q *Queries) ProgramExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, programExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const programSummary = `-- name: ProgramSummary :many
SELECT
    pq.id                                                               AS quota_id,
    pq.capacity                                                         AS quota_capacity,
    (SELECT COUNT(*)
     FROM enrollments e
     WHERE e.program_id = $1
       AND e.year = $2
       AND e.status != 'cancelled'
       AND e.deleted_at IS NULL)::int4                                  AS enrolled_count,
    p.name                                                              AS program_name
FROM program_quotas pq
JOIN programs p
    ON p.id = pq.program_id
    AND p.deleted_at IS NULL
WHERE pq.program_id = $1
  AND pq.year = $2
  AND pq.deleted_at IS NULL
LIMIT 201
`

type ProgramSummaryParams struct {
	ProgramID pgtype.UUID
	Year      int32
}

type ProgramSummaryRow struct {
	QuotaID       pgtype.UUID
	QuotaCapacity int32
	EnrolledCount int32
	ProgramName   string
}

func (q *Queries) ProgramSummary(ctx context.Context, arg ProgramSummaryParams) ([]ProgramSummaryRow, error) {
	rows, err := q.db.Query(ctx, programSummary, arg.ProgramID, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProgramSummaryRow
	for rows.Next() {
		var i ProgramSummaryRow
		if err := rows.Scan(
			&i.QuotaID,
			&i.QuotaCapacity,
			&i.EnrolledCount,
			&i.ProgramName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const studentExists = `-- name: StudentExists :one
SELECT EXISTS(
    SELECT 1 FROM student_profiles WHERE user_id = $1 AND deleted_at IS NULL
) AS exists
`

func (q *Queries) StudentExists(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, studentExists, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
