// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package authdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	CreatedBy    pgtype.UUID
	UpdatedBy    pgtype.UUID
	DeletedAt    pgtype.Timestamptz
}
