// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package profilesdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Permission struct {
	ID          pgtype.UUID
	Code        string
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Role struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type RolePermission struct {
	RoleID       pgtype.UUID
	PermissionID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

type StudentProfile struct {
	UserID        pgtype.UUID
	AdmissionYear int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	CreatedBy     pgtype.UUID
	UpdatedBy     pgtype.UUID
}

type TeacherProfile struct {
	UserID     pgtype.UUID
	Department pgtype.Text
	Title      pgtype.Text
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	CreatedBy  pgtype.UUID
	UpdatedBy  pgtype.UUID
}

type TeacherQualification struct {
	ID        pgtype.UUID
	TeacherID pgtype.UUID
	Degree    string
	Year      int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	CreatedBy    pgtype.UUID
	UpdatedBy    pgtype.UUID
	DeletedAt    pgtype.Timestamptz
}

type UserProfile struct {
	UserID                pgtype.UUID
	GivenNames            string
	LastNamePaternal      string
	LastNameMaternal      pgtype.Text
	NationalIDType        string
	NationalID            string
	BirthDate             pgtype.Date
	Phone                 pgtype.Text
	PersonalEmail         pgtype.Text
	AddressStreet         pgtype.Text
	Commune               pgtype.Text
	Region                pgtype.Text
	Country               pgtype.Text
	PostalCode            pgtype.Text
	Sex                   pgtype.Text
	Nationality           pgtype.Text
	PhotoUrl              pgtype.Text
	EmergencyContactName  pgtype.Text
	EmergencyContactPhone pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
	CreatedBy             pgtype.UUID
	UpdatedBy             pgtype.UUID
}

type UserRole struct {
	UserID    pgtype.UUID
	RoleID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}
