// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package profilesdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTeacherQualification = `-- name: AddTeacherQualification :one
INSERT INTO teacher_qualifications (
    teacher_id,
    degree,
    year,
    created_by,
    updated_by
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, teacher_id, degree, year, created_at, updated_at, deleted_at, created_by, updated_by
`

type AddTeacherQualificationParams struct {
	TeacherID pgtype.UUID
	Degree    string
	Year      int32
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
}

func (q *Queries) AddTeacherQualification(ctx context.Context, arg AddTeacherQualificationParams) (TeacherQualification, error) {
	row := q.db.QueryRow(ctx, addTeacherQualification,
		arg.TeacherID,
		arg.Degree,
		arg.Year,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i TeacherQualification
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Degree,
		&i.Year,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getOwnProfile = `-- name: GetOwnProfile :one
SELECT user_id, given_names, last_name_paternal, last_name_maternal, national_id_type, national_id, birth_date, phone, personal_email, address_street, commune, region, country, postal_code, sex, nationality, photo_url, emergency_contact_name, emergency_contact_phone, created_at, updated_at, deleted_at, created_by, updated_by
FROM user_profiles
WHERE user_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetOwnProfile(ctx context.Context, userID pgtype.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getOwnProfile, userID)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.GivenNames,
		&i.LastNamePaternal,
		&i.LastNameMaternal,
		&i.NationalIDType,
		&i.NationalID,
		&i.BirthDate,
		&i.Phone,
		&i.PersonalEmail,
		&i.AddressStreet,
		&i.Commune,
		&i.Region,
		&i.Country,
		&i.PostalCode,
		&i.Sex,
		&i.Nationality,
		&i.PhotoUrl,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getStudentProfile = `-- name: GetStudentProfile :one
SELECT user_id, admission_year, created_at, updated_at, deleted_at, created_by, updated_by
FROM student_profiles
WHERE user_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetStudentProfile(ctx context.Context, userID pgtype.UUID) (StudentProfile, error) {
	row := q.db.QueryRow(ctx, getStudentProfile, userID)
	var i StudentProfile
	err := row.Scan(
		&i.UserID,
		&i.AdmissionYear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getTeacherProfile = `-- name: GetTeacherProfile :one
SELECT user_id, department, title, created_at, updated_at, deleted_at, created_by, updated_by
FROM teacher_profiles
WHERE user_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetTeacherProfile(ctx context.Context, userID pgtype.UUID) (TeacherProfile, error) {
	row := q.db.QueryRow(ctx, getTeacherProfile, userID)
	var i TeacherProfile
	err := row.Scan(
		&i.UserID,
		&i.Department,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT user_id, given_names, last_name_paternal, last_name_maternal, national_id_type, national_id, birth_date, phone, personal_email, address_street, commune, region, country, postal_code, sex, nationality, photo_url, emergency_contact_name, emergency_contact_phone, created_at, updated_at, deleted_at, created_by, updated_by
FROM user_profiles
WHERE user_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUserProfile(ctx context.Context, userID pgtype.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfile, userID)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.GivenNames,
		&i.LastNamePaternal,
		&i.LastNameMaternal,
		&i.NationalIDType,
		&i.NationalID,
		&i.BirthDate,
		&i.Phone,
		&i.PersonalEmail,
		&i.AddressStreet,
		&i.Commune,
		&i.Region,
		&i.Country,
		&i.PostalCode,
		&i.Sex,
		&i.Nationality,
		&i.PhotoUrl,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listTeacherQualifications = `-- name: ListTeacherQualifications :many
SELECT id, teacher_id, degree, year, created_at, updated_at, deleted_at, created_by, updated_by
FROM teacher_qualifications
WHERE teacher_id = $1
  AND deleted_at IS NULL
ORDER BY year, created_at
`

func (q *Queries) ListTeacherQualifications(ctx context.Context, teacherID pgtype.UUID) ([]TeacherQualification, error) {
	rows, err := q.db.Query(ctx, listTeacherQualifications, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TeacherQualification
	for rows.Next() {
		var i TeacherQualification
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.Degree,
			&i.Year,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOwnProfile = `-- name: UpsertOwnProfile :one
UPDATE user_profiles SET
    birth_date              = COALESCE($1,              birth_date),
    phone                   = COALESCE($2,                   phone),
    personal_email          = COALESCE($3,          personal_email),
    address_street          = COALESCE($4,          address_street),
    commune                 = COALESCE($5,                 commune),
    region                  = COALESCE($6,                  region),
    country                 = COALESCE($7,                 country),
    postal_code             = COALESCE($8,             postal_code),
    photo_url               = COALESCE($9,               photo_url),
    emergency_contact_name  = COALESCE($10,  emergency_contact_name),
    emergency_contact_phone = COALESCE($11, emergency_contact_phone),
    updated_at = now(),
    updated_by = $12
WHERE user_id = $13
  AND deleted_at IS NULL
RETURNING user_id, given_names, last_name_paternal, last_name_maternal, national_id_type, national_id, birth_date, phone, personal_email, address_street, commune, region, country, postal_code, sex, nationality, photo_url, emergency_contact_name, emergency_contact_phone, created_at, updated_at, deleted_at, created_by, updated_by
`

type UpsertOwnProfileParams struct {
	BirthDate             pgtype.Date
	Phone                 pgtype.Text
	PersonalEmail         pgtype.Text
	AddressStreet         pgtype.Text
	Commune               pgtype.Text
	Region                pgtype.Text
	Country               pgtype.Text
	PostalCode            pgtype.Text
	PhotoUrl              pgtype.Text
	EmergencyContactName  pgtype.Text
	EmergencyContactPhone pgtype.Text
	UpdatedBy             pgtype.UUID
	UserID                pgtype.UUID
}

func (q *Queries) UpsertOwnProfile(ctx context.Context, arg UpsertOwnProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, upsertOwnProfile,
		arg.BirthDate,
		arg.Phone,
		arg.PersonalEmail,
		arg.AddressStreet,
		arg.Commune,
		arg.Region,
		arg.Country,
		arg.PostalCode,
		arg.PhotoUrl,
		arg.EmergencyContactName,
		arg.EmergencyContactPhone,
		arg.UpdatedBy,
		arg.UserID,
	)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.GivenNames,
		&i.LastNamePaternal,
		&i.LastNameMaternal,
		&i.NationalIDType,
		&i.NationalID,
		&i.BirthDate,
		&i.Phone,
		&i.PersonalEmail,
		&i.AddressStreet,
		&i.Commune,
		&i.Region,
		&i.Country,
		&i.PostalCode,
		&i.Sex,
		&i.Nationality,
		&i.PhotoUrl,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertStudentProfile = `-- name: UpsertStudentProfile :one
INSERT INTO student_profiles (
    user_id,
    admission_year,
    created_by,
    updated_by
) VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE SET
    admission_year = EXCLUDED.admission_year,
    updated_at     = now(),
    updated_by     = EXCLUDED.updated_by
RETURNING user_id, admission_year, created_at, updated_at, deleted_at, created_by, updated_by
`

type UpsertStudentProfileParams struct {
	UserID        pgtype.UUID
	AdmissionYear int32
	CreatedBy     pgtype.UUID
	UpdatedBy     pgtype.UUID
}

func (q *Queries) UpsertStudentProfile(ctx context.Context, arg UpsertStudentProfileParams) (StudentProfile, error) {
	row := q.db.QueryRow(ctx, upsertStudentProfile,
		arg.UserID,
		arg.AdmissionYear,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i StudentProfile
	err := row.Scan(
		&i.UserID,
		&i.AdmissionYear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertTeacherProfile = `-- name: UpsertTeacherProfile :one
INSERT INTO teacher_profiles (
    user_id,
    department,
    title,
    created_by,
    updated_by
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE SET
    department = EXCLUDED.department,
    title      = EXCLUDED.title,
    updated_at = now(),
    updated_by = EXCLUDED.updated_by
RETURNING user_id, department, title, created_at, updated_at, deleted_at, created_by, updated_by
`

type UpsertTeacherProfileParams struct {
	UserID     pgtype.UUID
	Department pgtype.Text
	Title      pgtype.Text
	CreatedBy  pgtype.UUID
	UpdatedBy  pgtype.UUID
}

func (q *Queries) UpsertTeacherProfile(ctx context.Context, arg UpsertTeacherProfileParams) (TeacherProfile, error) {
	row := q.db.QueryRow(ctx, upsertTeacherProfile,
		arg.UserID,
		arg.Department,
		arg.Title,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i TeacherProfile
	err := row.Scan(
		&i.UserID,
		&i.Department,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertUserProfile = `-- name: UpsertUserProfile :one
INSERT INTO user_profiles (
    user_id,
    given_names,
    last_name_paternal,
    last_name_maternal,
    national_id_type,
    national_id,
    birth_date,
    phone,
    personal_email,
    address_street,
    commune,
    region,
    country,
    postal_code,
    sex,
    nationality,
    photo_url,
    emergency_contact_name,
    emergency_contact_phone,
    created_by,
    updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21
)
ON CONFLICT (user_id) DO UPDATE SET
    given_names              = EXCLUDED.given_names,
    last_name_paternal       = EXCLUDED.last_name_paternal,
    last_name_maternal       = EXCLUDED.last_name_maternal,
    national_id_type         = EXCLUDED.national_id_type,
    national_id              = EXCLUDED.national_id,
    birth_date               = EXCLUDED.birth_date,
    phone                    = EXCLUDED.phone,
    personal_email           = EXCLUDED.personal_email,
    address_street           = EXCLUDED.address_street,
    commune                  = EXCLUDED.commune,
    region                   = EXCLUDED.region,
    country                  = EXCLUDED.country,
    postal_code              = EXCLUDED.postal_code,
    sex                      = EXCLUDED.sex,
    nationality              = EXCLUDED.nationality,
    photo_url                = EXCLUDED.photo_url,
    emergency_contact_name   = EXCLUDED.emergency_contact_name,
    emergency_contact_phone  = EXCLUDED.emergency_contact_phone,
    updated_at               = now(),
    updated_by               = EXCLUDED.updated_by
RETURNING user_id, given_names, last_name_paternal, last_name_maternal, national_id_type, national_id, birth_date, phone, personal_email, address_street, commune, region, country, postal_code, sex, nationality, photo_url, emergency_contact_name, emergency_contact_phone, created_at, updated_at, deleted_at, created_by, updated_by
`

type UpsertUserProfileParams struct {
	UserID                pgtype.UUID
	GivenNames            string
	LastNamePaternal      string
	LastNameMaternal      pgtype.Text
	NationalIDType        string
	NationalID            string
	BirthDate             pgtype.Date
	Phone                 pgtype.Text
	PersonalEmail         pgtype.Text
	AddressStreet         pgtype.Text
	Commune               pgtype.Text
	Region                pgtype.Text
	Country               pgtype.Text
	PostalCode            pgtype.Text
	Sex                   pgtype.Text
	Nationality           pgtype.Text
	PhotoUrl              pgtype.Text
	EmergencyContactName  pgtype.Text
	EmergencyContactPhone pgtype.Text
	CreatedBy             pgtype.UUID
	UpdatedBy             pgtype.UUID
}

func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, upsertUserProfile,
		arg.UserID,
		arg.GivenNames,
		arg.LastNamePaternal,
		arg.LastNameMaternal,
		arg.NationalIDType,
		arg.NationalID,
		arg.BirthDate,
		arg.Phone,
		arg.PersonalEmail,
		arg.AddressStreet,
		arg.Commune,
		arg.Region,
		arg.Country,
		arg.PostalCode,
		arg.Sex,
		arg.Nationality,
		arg.PhotoUrl,
		arg.EmergencyContactName,
		arg.EmergencyContactPhone,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.GivenNames,
		&i.LastNamePaternal,
		&i.LastNameMaternal,
		&i.NationalIDType,
		&i.NationalID,
		&i.BirthDate,
		&i.Phone,
		&i.PersonalEmail,
		&i.AddressStreet,
		&i.Commune,
		&i.Region,
		&i.Country,
		&i.PostalCode,
		&i.Sex,
		&i.Nationality,
		&i.PhotoUrl,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
