// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package profilesdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddTeacherQualification(ctx context.Context, arg AddTeacherQualificationParams) (TeacherQualification, error)
	GetOwnProfile(ctx context.Context, userID pgtype.UUID) (UserProfile, error)
	GetStudentProfile(ctx context.Context, userID pgtype.UUID) (StudentProfile, error)
	GetTeacherProfile(ctx context.Context, userID pgtype.UUID) (TeacherProfile, error)
	GetUserProfile(ctx context.Context, userID pgtype.UUID) (UserProfile, error)
	ListTeacherQualifications(ctx context.Context, teacherID pgtype.UUID) ([]TeacherQualification, error)
	UpsertOwnProfile(ctx context.Context, arg UpsertOwnProfileParams) (UserProfile, error)
	UpsertStudentProfile(ctx context.Context, arg UpsertStudentProfileParams) (StudentProfile, error)
	UpsertTeacherProfile(ctx context.Context, arg UpsertTeacherProfileParams) (TeacherProfile, error)
	UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (UserProfile, error)
}

var _ Querier = (*Queries)(nil)
