// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gradesdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Counts grades referencing any live evaluation of a course.
	// Used to gate RecreateEvaluationScheme: non-zero means the scheme is in use.
	CountGradesForEvaluations(ctx context.Context, courseID pgtype.UUID) (int64, error)
	// Counts live evaluations for a course. Used to check scheme completeness.
	CountLiveEvaluationsForCourse(ctx context.Context, courseID pgtype.UUID) (int64, error)
	// Fetches an evaluation by primary key (any state, for existence checks).
	GetEvaluationByID(ctx context.Context, id pgtype.UUID) (Evaluation, error)
	// Fetches a grade by primary key.
	GetGradeByID(ctx context.Context, id pgtype.UUID) (Grade, error)
	// Fetches a grade by primary key only if the caller is in section_teachers for the grade's section.
	// Returns no rows if the grade does not exist or the caller is not in that section.
	GetGradeByIDForTeacher(ctx context.Context, arg GetGradeByIDForTeacherParams) (Grade, error)
	// Fetches a grade by its unique business key (used to read current version on conflict).
	GetGradeByKey(ctx context.Context, arg GetGradeByKeyParams) (Grade, error)
	// Locks the section_enrollment row FOR UPDATE and resolves section_id and course_id.
	// This is the serialization point for all concurrent grade writes targeting the same SE.
	GetSectionEnrollmentForGrade(ctx context.Context, id pgtype.UUID) (GetSectionEnrollmentForGradeRow, error)
	// Records an audit event for a grade value change (old value → new value).
	// actor_id may be NULL for system-initiated changes.
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	// Cross-domain read strategy: queries here read sections and section_teachers directly
	// as the canonical cross-domain join pattern for this codebase. The single transaction
	// boundary makes all checks atomic.
	// Inserts one evaluation for a course scheme with an explicit position.
	InsertEvaluation(ctx context.Context, arg InsertEvaluationParams) (Evaluation, error)
	// Inserts a new grade. ON CONFLICT DO NOTHING so that the caller can detect
	// whether an existing grade was hit (0 rows returned) or a new one was created.
	InsertGrade(ctx context.Context, arg InsertGradeParams) (Grade, error)
	// Checks whether a user is in section_teachers for the given section.
	IsTeacherForSection(ctx context.Context, arg IsTeacherForSectionParams) (bool, error)
	// Returns all live evaluations for a course ordered by position.
	ListEvaluationsForCourse(ctx context.Context, courseID pgtype.UUID) ([]Evaluation, error)
	// Lists all grades for a section_enrollment (used for weighted-final computation).
	ListGradesBySectionEnrollment(ctx context.Context, sectionEnrollmentID pgtype.UUID) ([]Grade, error)
	// Lists grades for all section_enrollments in a section.
	// Caller must scope by their section_teachers membership in the service layer.
	ListGradesForSection(ctx context.Context, sectionID pgtype.UUID) ([]Grade, error)
	// Lists grades for all section_enrollments in a section, scoped to a teacher.
	// Returns empty if the teacher is not in section_teachers for the section.
	ListGradesForSectionByTeacher(ctx context.Context, arg ListGradesForSectionByTeacherParams) ([]Grade, error)
	// Keyset-paginated list of grades for a section, scoped to a teacher.
	// Returns empty if the teacher is not in section_teachers for the section.
	// Ordered by g.id DESC. page_token is the exclusive upper bound on g.id (NULL = start).
	ListGradesForSectionByTeacherPaged(ctx context.Context, arg ListGradesForSectionByTeacherPagedParams) ([]Grade, error)
	// Keyset-paginated list of grades for a section (admin path, no teacher scope).
	// Ordered by g.id DESC. page_token is the exclusive upper bound on g.id (NULL = start).
	ListGradesForSectionPaged(ctx context.Context, arg ListGradesForSectionPagedParams) ([]Grade, error)
	// Lists all grades for a student by joining through enrollments.
	ListOwnGrades(ctx context.Context, studentID pgtype.UUID) ([]Grade, error)
	// Keyset-paginated list of grades for a student (via enrollments join).
	// Ordered by g.id DESC. page_token is the exclusive upper bound on g.id (NULL = start).
	ListOwnGradesPaged(ctx context.Context, arg ListOwnGradesPagedParams) ([]Grade, error)
	// Acquires FOR UPDATE row locks on all live evaluation rows for a course.
	// Must run before CountGradesForEvaluations inside RecreateEvaluationSchemeTx so that
	// a concurrent RecordGradeTx (which holds FOR KEY SHARE on the evaluation via the FK)
	// either blocks this recreate until it commits (and is then counted) or is blocked by
	// this lock until the recreate commits — preventing a TOCTOU race under READ COMMITTED.
	LockEvaluationsForCourse(ctx context.Context, courseID pgtype.UUID) ([]pgtype.UUID, error)
	// Soft-deletes all live evaluations for a course (RecreateEvaluationScheme path).
	SoftDeleteEvaluationsForCourse(ctx context.Context, courseID pgtype.UUID) error
	// Applies an optimistic-lock update: increments version and sets updated fields.
	// Returns 0 rows when the version does not match (conflict).
	UpdateGradeByVersion(ctx context.Context, arg UpdateGradeByVersionParams) (Grade, error)
}

var _ Querier = (*Queries)(nil)
