// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package gradesdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGradesForEvaluations = `-- name: CountGradesForEvaluations :one
SELECT COUNT(*) FROM grades g
JOIN evaluations e ON e.id = g.evaluation_id
WHERE e.course_id = $1 AND e.deleted_at IS NULL
`

// Counts grades referencing any live evaluation of a course.
// Used to gate RecreateEvaluationScheme: non-zero means the scheme is in use.
func (q *Queries) CountGradesForEvaluations(ctx context.Context, courseID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGradesForEvaluations, courseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLiveEvaluationsForCourse = `-- name: CountLiveEvaluationsForCourse :one
SELECT COUNT(*) FROM evaluations
WHERE course_id = $1 AND deleted_at IS NULL
`

// Counts live evaluations for a course. Used to check scheme completeness.
func (q *Queries) CountLiveEvaluationsForCourse(ctx context.Context, courseID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveEvaluationsForCourse, courseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGradeByID = `-- name: GetGradeByID :one
SELECT id, evaluation_id, section_enrollment_id, graded_by, value, evaluated_at, version, created_at, updated_at, created_by, updated_by, deleted_at FROM grades
WHERE id = $1 AND deleted_at IS NULL
`

// Fetches a grade by primary key.
func (q *Queries) GetGradeByID(ctx context.Context, id pgtype.UUID) (Grade, error) {
	row := q.db.QueryRow(ctx, getGradeByID, id)
	var i Grade
	err := row.Scan(
		&i.ID,
		&i.EvaluationID,
		&i.SectionEnrollmentID,
		&i.GradedBy,
		&i.Value,
		&i.EvaluatedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getGradeByKey = `-- name: GetGradeByKey :one
SELECT id, evaluation_id, section_enrollment_id, graded_by, value, evaluated_at, version, created_at, updated_at, created_by, updated_by, deleted_at FROM grades
WHERE evaluation_id = $1
  AND section_enrollment_id = $2
  AND deleted_at IS NULL
`

type GetGradeByKeyParams struct {
	EvaluationID        pgtype.UUID
	SectionEnrollmentID pgtype.UUID
}

// Fetches a grade by its unique business key (used to read current version on conflict).
func (q *Queries) GetGradeByKey(ctx context.Context, arg GetGradeByKeyParams) (Grade, error) {
	row := q.db.QueryRow(ctx, getGradeByKey, arg.EvaluationID, arg.SectionEnrollmentID)
	var i Grade
	err := row.Scan(
		&i.ID,
		&i.EvaluationID,
		&i.SectionEnrollmentID,
		&i.GradedBy,
		&i.Value,
		&i.EvaluatedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getSectionEnrollmentForGrade = `-- name: GetSectionEnrollmentForGrade :one
SELECT
    se.id,
    se.enrollment_id,
    se.section_id,
    se.status,
    se.final_grade,
    s.course_id,
    e.student_id
FROM section_enrollments se
JOIN sections s ON s.id = se.section_id
JOIN enrollments e ON e.id = se.enrollment_id
WHERE se.id = $1 AND se.deleted_at IS NULL
FOR UPDATE OF se
`

type GetSectionEnrollmentForGradeRow struct {
	ID           pgtype.UUID
	EnrollmentID pgtype.UUID
	SectionID    pgtype.UUID
	Status       string
	FinalGrade   pgtype.Numeric
	CourseID     pgtype.UUID
	StudentID    pgtype.UUID
}

// Locks the section_enrollment row FOR UPDATE and resolves section_id and course_id.
// This is the serialization point for all concurrent grade writes targeting the same SE.
func (q *Queries) GetSectionEnrollmentForGrade(ctx context.Context, id pgtype.UUID) (GetSectionEnrollmentForGradeRow, error) {
	row := q.db.QueryRow(ctx, getSectionEnrollmentForGrade, id)
	var i GetSectionEnrollmentForGradeRow
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.SectionID,
		&i.Status,
		&i.FinalGrade,
		&i.CourseID,
		&i.StudentID,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (actor_id, action, entity, entity_id, detail)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditLogParams struct {
	ActorID  pgtype.UUID
	Action   string
	Entity   string
	EntityID pgtype.UUID
	Detail   []byte
}

// Records an audit event for a grade value change (old value → new value).
// actor_id may be NULL for system-initiated changes.
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Detail,
	)
	return err
}

const insertEvaluation = `-- name: InsertEvaluation :one

INSERT INTO evaluations (course_id, weight, position)
VALUES ($1, $2, $3)
RETURNING id, course_id, weight, position, created_at, updated_at, deleted_at
`

type InsertEvaluationParams struct {
	CourseID pgtype.UUID
	Weight   pgtype.Numeric
	Position int32
}

// Cross-domain read strategy: queries here read sections and section_teachers directly
// as the canonical cross-domain join pattern for this codebase. The single transaction
// boundary makes all checks atomic.
// Inserts one evaluation for a course scheme with an explicit position.
func (q *Queries) InsertEvaluation(ctx context.Context, arg InsertEvaluationParams) (Evaluation, error) {
	row := q.db.QueryRow(ctx, insertEvaluation, arg.CourseID, arg.Weight, arg.Position)
	var i Evaluation
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Weight,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertGrade = `-- name: InsertGrade :one
INSERT INTO grades (evaluation_id, section_enrollment_id, graded_by, value, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (evaluation_id, section_enrollment_id) DO NOTHING
RETURNING id, evaluation_id, section_enrollment_id, graded_by, value, evaluated_at, version, created_at, updated_at, created_by, updated_by, deleted_at
`

type InsertGradeParams struct {
	EvaluationID        pgtype.UUID
	SectionEnrollmentID pgtype.UUID
	GradedBy            pgtype.UUID
	Value               pgtype.Numeric
	CreatedBy           pgtype.UUID
	UpdatedBy           pgtype.UUID
}

// Inserts a new grade. ON CONFLICT DO NOTHING so that the caller can detect
// whether an existing grade was hit (0 rows returned) or a new one was created.
func (q *Queries) InsertGrade(ctx context.Context, arg InsertGradeParams) (Grade, error) {
	row := q.db.QueryRow(ctx, insertGrade,
		arg.EvaluationID,
		arg.SectionEnrollmentID,
		arg.GradedBy,
		arg.Value,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Grade
	err := row.Scan(
		&i.ID,
		&i.EvaluationID,
		&i.SectionEnrollmentID,
		&i.GradedBy,
		&i.Value,
		&i.EvaluatedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const isTeacherForSection = `-- name: IsTeacherForSection :one
SELECT EXISTS(
    SELECT 1 FROM section_teachers
    WHERE section_id = $1 AND teacher_id = $2
) AS exists
`

type IsTeacherForSectionParams struct {
	SectionID pgtype.UUID
	TeacherID pgtype.UUID
}

// Checks whether a user is in section_teachers for the given section.
func (q *Queries) IsTeacherForSection(ctx context.Context, arg IsTeacherForSectionParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTeacherForSection, arg.SectionID, arg.TeacherID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listEvaluationsForCourse = `-- name: ListEvaluationsForCourse :many
SELECT id, course_id, weight, position, created_at, updated_at, deleted_at FROM evaluations
WHERE course_id = $1 AND deleted_at IS NULL
ORDER BY position
`

// Returns all live evaluations for a course ordered by position.
func (q *Queries) ListEvaluationsForCourse(ctx context.Context, courseID pgtype.UUID) ([]Evaluation, error) {
	rows, err := q.db.Query(ctx, listEvaluationsForCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Evaluation
	for rows.Next() {
		var i Evaluation
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Weight,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGradesBySectionEnrollment = `-- name: ListGradesBySectionEnrollment :many
SELECT id, evaluation_id, section_enrollment_id, graded_by, value, evaluated_at, version, created_at, updated_at, created_by, updated_by, deleted_at FROM grades
WHERE section_enrollment_id = $1 AND deleted_at IS NULL
`

// Lists all grades for a section_enrollment (used for weighted-final computation).
func (q *Queries) ListGradesBySectionEnrollment(ctx context.Context, sectionEnrollmentID pgtype.UUID) ([]Grade, error) {
	rows, err := q.db.Query(ctx, listGradesBySectionEnrollment, sectionEnrollmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Grade
	for rows.Next() {
		var i Grade
		if err := rows.Scan(
			&i.ID,
			&i.EvaluationID,
			&i.SectionEnrollmentID,
			&i.GradedBy,
			&i.Value,
			&i.EvaluatedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGradesForSection = `-- name: ListGradesForSection :many
SELECT g.id, g.evaluation_id, g.section_enrollment_id, g.graded_by, g.value, g.evaluated_at, g.version, g.created_at, g.updated_at, g.created_by, g.updated_by, g.deleted_at
FROM grades g
JOIN section_enrollments se ON se.id = g.section_enrollment_id
WHERE se.section_id = $1
  AND g.deleted_at IS NULL
  AND se.deleted_at IS NULL
`

// Lists grades for all section_enrollments in a section.
// Caller must scope by their section_teachers membership in the service layer.
func (q *Queries) ListGradesForSection(ctx context.Context, sectionID pgtype.UUID) ([]Grade, error) {
	rows, err := q.db.Query(ctx, listGradesForSection, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Grade
	for rows.Next() {
		var i Grade
		if err := rows.Scan(
			&i.ID,
			&i.EvaluationID,
			&i.SectionEnrollmentID,
			&i.GradedBy,
			&i.Value,
			&i.EvaluatedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnGrades = `-- name: ListOwnGrades :many
SELECT g.id, g.evaluation_id, g.section_enrollment_id, g.graded_by, g.value, g.evaluated_at, g.version, g.created_at, g.updated_at, g.created_by, g.updated_by, g.deleted_at
FROM grades g
JOIN section_enrollments se ON se.id = g.section_enrollment_id
JOIN enrollments e ON e.id = se.enrollment_id
WHERE e.student_id = $1
  AND g.deleted_at IS NULL
  AND se.deleted_at IS NULL
`

// Lists all grades for a student by joining through enrollments.
func (q *Queries) ListOwnGrades(ctx context.Context, studentID pgtype.UUID) ([]Grade, error) {
	rows, err := q.db.Query(ctx, listOwnGrades, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Grade
	for rows.Next() {
		var i Grade
		if err := rows.Scan(
			&i.ID,
			&i.EvaluationID,
			&i.SectionEnrollmentID,
			&i.GradedBy,
			&i.Value,
			&i.EvaluatedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEvaluationsForCourse = `-- name: SoftDeleteEvaluationsForCourse :exec
UPDATE evaluations
SET deleted_at = now(), updated_at = now()
WHERE course_id = $1 AND deleted_at IS NULL
`

// Soft-deletes all live evaluations for a course (RecreateEvaluationScheme path).
func (q *Queries) SoftDeleteEvaluationsForCourse(ctx context.Context, courseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteEvaluationsForCourse, courseID)
	return err
}

const updateGradeByVersion = `-- name: UpdateGradeByVersion :one
UPDATE grades
SET value      = $3,
    version    = version + 1,
    graded_by  = $4,
    evaluated_at = now(),
    updated_at = now(),
    updated_by = $5
WHERE id = $1
  AND version = $2
RETURNING id, evaluation_id, section_enrollment_id, graded_by, value, evaluated_at, version, created_at, updated_at, created_by, updated_by, deleted_at
`

type UpdateGradeByVersionParams struct {
	ID        pgtype.UUID
	Version   int32
	Value     pgtype.Numeric
	GradedBy  pgtype.UUID
	UpdatedBy pgtype.UUID
}

// Applies an optimistic-lock update: increments version and sets updated fields.
// Returns 0 rows when the version does not match (conflict).
func (q *Queries) UpdateGradeByVersion(ctx context.Context, arg UpdateGradeByVersionParams) (Grade, error) {
	row := q.db.QueryRow(ctx, updateGradeByVersion,
		arg.ID,
		arg.Version,
		arg.Value,
		arg.GradedBy,
		arg.UpdatedBy,
	)
	var i Grade
	err := row.Scan(
		&i.ID,
		&i.EvaluationID,
		&i.SectionEnrollmentID,
		&i.GradedBy,
		&i.Value,
		&i.EvaluatedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}
