// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package auditlogsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_id, action, entity, entity_id, detail, created_at
FROM audit_logs
WHERE entity = $1
  AND entity_id = $2
  AND ($3::uuid IS NULL      OR actor_id   = $3::uuid)
  AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
  AND ($5::timestamptz   IS NULL OR created_at <= $5::timestamptz)
  AND ($6::uuid IS NULL    OR id          < $6::uuid)
ORDER BY id DESC
LIMIT $7::int
`

type ListAuditLogsParams struct {
	Entity      string
	EntityID    pgtype.UUID
	ActorID     pgtype.UUID
	CreatedFrom pgtype.Timestamptz
	CreatedTo   pgtype.Timestamptz
	PageToken   pgtype.UUID
	RowLimit    int32
}

// Keyset pagination over the append-only audit_logs table, scoped to one entity instance.
// entity + entity_id are required and ride audit_logs_entity_idx. Optional actor_id and
// created_at range are residual filters. Newest-first (id DESC, UUIDv7 = reverse chrono).
func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.Entity,
		arg.EntityID,
		arg.ActorID,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.PageToken,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
