// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package auditlogsdb

import (
	"context"
)

type Querier interface {
	// Keyset pagination over the append-only audit_logs table, scoped to one entity instance.
	// entity + entity_id are required and ride audit_logs_entity_idx. Optional actor_id and
	// created_at range are residual filters. Newest-first (id DESC, UUIDv7 = reverse chrono).
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
}

var _ Querier = (*Queries)(nil)
