// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package iamdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Inserts a user_roles row for the given user and role name.
	// Idempotent: ON CONFLICT DO NOTHING on the composite PK means a re-assign
	// returns 0 affected rows without error. The service layer writes an audit
	// entry on every call (including the 0-row no-op) per EC-05.
	AssignRole(ctx context.Context, arg AssignRoleParams) (int64, error)
	// Counts how many users currently hold the admin role.
	// Used by the privilege-escalation guard to prevent removing the last admin.
	CountAdmins(ctx context.Context) (int32, error)
	// Returns identity and profile columns for a single non-deleted user by UUID.
	// LEFT JOIN user_profiles so users without a profile row still return.
	GetUserByID(ctx context.Context, userID pgtype.UUID) (GetUserByIDRow, error)
	// Returns role names for a single user, sorted alphabetically.
	GetUserRoles(ctx context.Context, userID pgtype.UUID) ([]string, error)
	// Records a role mutation audit event (role.assign or role.revoke).
	// Mirrors internal/grades/query.sql:InsertAuditLog (co-located per-slice copy).
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	// Keyset pagination over the users table with optional search and inline roles.
	// Ordered newest-first (id DESC, UUIDv7 = reverse chronological). display_name
	// derived via LEFT JOIN to user_profiles; roles aggregated in-query (no N+1).
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	// Hard-deletes the user_roles row for the given user and role name.
	// Returns 0 rows affected when the user does not have the role (→ ErrNotFound).
	RevokeRole(ctx context.Context, arg RevokeRoleParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
