// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package iamdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignRole = `-- name: AssignRole :execrows
INSERT INTO user_roles (user_id, role_id)
SELECT $1, r.id FROM roles r WHERE r.name = $2
ON CONFLICT (user_id, role_id) DO NOTHING
`

type AssignRoleParams struct {
	UserID   pgtype.UUID
	RoleName string
}

// Assigns a role to a user. Idempotent via ON CONFLICT DO NOTHING on the composite PK.
func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignRole, arg.UserID, arg.RoleName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*)::int FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE r.name = 'admin'
`

// Returns the count of users currently holding the admin role.
func (q *Queries) CountAdmins(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT u.id, u.email, u.disabled_at,
       p.given_names, p.last_name_paternal
FROM users u
LEFT JOIN user_profiles p ON p.user_id = u.id AND p.deleted_at IS NULL
WHERE u.id = $1 AND u.deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID               pgtype.UUID
	Email            string
	DisabledAt       pgtype.Timestamptz
	GivenNames       pgtype.Text
	LastNamePaternal pgtype.Text
}

// Returns identity and profile columns for a single non-deleted user by UUID.
// LEFT JOIN user_profiles so users without a profile row still return.
func (q *Queries) GetUserByID(ctx context.Context, userID pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisabledAt,
		&i.GivenNames,
		&i.LastNamePaternal,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.name FROM roles r
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
ORDER BY r.name
`

// Returns role names for a single user, sorted alphabetically.
func (q *Queries) GetUserRoles(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (actor_id, action, entity, entity_id, detail)
VALUES ($1, $2, $3,
        $4, $5)
`

type InsertAuditLogParams struct {
	ActorID  pgtype.UUID
	Action   string
	Entity   string
	EntityID pgtype.UUID
	Detail   []byte
}

// Co-located audit log insertion (mirrors grades slice pattern).
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Detail,
	)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.email, u.disabled_at,
       p.given_names, p.last_name_paternal,
       (SELECT array_agg(r.name ORDER BY r.name)
        FROM user_roles ur
        JOIN roles r ON r.id = ur.role_id
        WHERE ur.user_id = u.id) AS roles
FROM users u
LEFT JOIN user_profiles p ON p.user_id = u.id AND p.deleted_at IS NULL
WHERE u.deleted_at IS NULL
  AND ($1::uuid IS NULL OR u.id < $1::uuid)
  AND ($2::text IS NULL
       OR u.email ILIKE '%' || $2 || '%'
       OR (p.given_names || ' ' || p.last_name_paternal) ILIKE '%' || $2 || '%')
ORDER BY u.id DESC
LIMIT $3::int
`

type ListUsersParams struct {
	PageToken pgtype.UUID
	Query     pgtype.Text
	RowLimit  int32
}

type ListUsersRow struct {
	ID               pgtype.UUID
	Email            string
	DisabledAt       pgtype.Timestamptz
	GivenNames       pgtype.Text
	LastNamePaternal pgtype.Text
	Roles            interface{}
}

// Keyset pagination over the users table with optional search and inline roles.
// Ordered newest-first (id DESC, UUIDv7 = reverse chronological). display_name
// derived via LEFT JOIN to user_profiles; roles aggregated in-query (no N+1).
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.PageToken, arg.Query, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisabledAt,
			&i.GivenNames,
			&i.LastNamePaternal,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRole = `-- name: RevokeRole :execrows
DELETE FROM user_roles ur USING roles r
WHERE ur.role_id = r.id
  AND ur.user_id = $1
  AND r.name = $2
`

type RevokeRoleParams struct {
	UserID   pgtype.UUID
	RoleName string
}

// Removes a role from a user by hard-deleting the user_roles row.
func (q *Queries) RevokeRole(ctx context.Context, arg RevokeRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRole, arg.UserID, arg.RoleName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
