/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedForbiddenRouteImport } from './routes/_authenticated/forbidden'
import { Route as AuthenticatedChooseAreaRouteImport } from './routes/_authenticated/choose-area'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/app/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAppSectionEnrollmentsRouteImport } from './routes/_authenticated/app/section-enrollments'
import { Route as AuthenticatedAppGradesRouteImport } from './routes/_authenticated/app/grades'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSectionEnrollmentsRouteImport } from './routes/_authenticated/admin/section-enrollments'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminGradesRouteImport } from './routes/_authenticated/admin/grades'
import { Route as AuthenticatedAdminEnrollmentsRouteImport } from './routes/_authenticated/admin/enrollments'
import { Route as AuthenticatedAdminAcademicsRouteImport } from './routes/_authenticated/admin/academics'
import { Route as AuthenticatedAdminGradesIndexRouteImport } from './routes/_authenticated/admin/grades.index'
import { Route as AuthenticatedAdminGradesSectionIdRouteImport } from './routes/_authenticated/admin/grades.$sectionId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedForbiddenRoute = AuthenticatedForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChooseAreaRoute = AuthenticatedChooseAreaRouteImport.update({
  id: '/choose-area',
  path: '/choose-area',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAppSectionEnrollmentsRoute =
  AuthenticatedAppSectionEnrollmentsRouteImport.update({
    id: '/section-enrollments',
    path: '/section-enrollments',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppGradesRoute = AuthenticatedAppGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSectionEnrollmentsRoute =
  AuthenticatedAdminSectionEnrollmentsRouteImport.update({
    id: '/section-enrollments',
    path: '/section-enrollments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGradesRoute =
  AuthenticatedAdminGradesRouteImport.update({
    id: '/grades',
    path: '/grades',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEnrollmentsRoute =
  AuthenticatedAdminEnrollmentsRouteImport.update({
    id: '/enrollments',
    path: '/enrollments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAcademicsRoute =
  AuthenticatedAdminAcademicsRouteImport.update({
    id: '/academics',
    path: '/academics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGradesIndexRoute =
  AuthenticatedAdminGradesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminGradesRoute,
  } as any)
const AuthenticatedAdminGradesSectionIdRoute =
  AuthenticatedAdminGradesSectionIdRouteImport.update({
    id: '/$sectionId',
    path: '/$sectionId',
    getParentRoute: () => AuthenticatedAdminGradesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/choose-area': typeof AuthenticatedChooseAreaRoute
  '/forbidden': typeof AuthenticatedForbiddenRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/academics': typeof AuthenticatedAdminAcademicsRoute
  '/admin/enrollments': typeof AuthenticatedAdminEnrollmentsRoute
  '/admin/grades': typeof AuthenticatedAdminGradesRouteWithChildren
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/section-enrollments': typeof AuthenticatedAdminSectionEnrollmentsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/app/grades': typeof AuthenticatedAppGradesRoute
  '/app/section-enrollments': typeof AuthenticatedAppSectionEnrollmentsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/admin/grades/$sectionId': typeof AuthenticatedAdminGradesSectionIdRoute
  '/admin/grades/': typeof AuthenticatedAdminGradesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/choose-area': typeof AuthenticatedChooseAreaRoute
  '/forbidden': typeof AuthenticatedForbiddenRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/academics': typeof AuthenticatedAdminAcademicsRoute
  '/admin/enrollments': typeof AuthenticatedAdminEnrollmentsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/section-enrollments': typeof AuthenticatedAdminSectionEnrollmentsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/app/grades': typeof AuthenticatedAppGradesRoute
  '/app/section-enrollments': typeof AuthenticatedAppSectionEnrollmentsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/admin/grades/$sectionId': typeof AuthenticatedAdminGradesSectionIdRoute
  '/admin/grades': typeof AuthenticatedAdminGradesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/_authenticated/choose-area': typeof AuthenticatedChooseAreaRoute
  '/_authenticated/forbidden': typeof AuthenticatedForbiddenRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/academics': typeof AuthenticatedAdminAcademicsRoute
  '/_authenticated/admin/enrollments': typeof AuthenticatedAdminEnrollmentsRoute
  '/_authenticated/admin/grades': typeof AuthenticatedAdminGradesRouteWithChildren
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/section-enrollments': typeof AuthenticatedAdminSectionEnrollmentsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/app/grades': typeof AuthenticatedAppGradesRoute
  '/_authenticated/app/section-enrollments': typeof AuthenticatedAppSectionEnrollmentsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/admin/grades/$sectionId': typeof AuthenticatedAdminGradesSectionIdRoute
  '/_authenticated/admin/grades/': typeof AuthenticatedAdminGradesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/app'
    | '/choose-area'
    | '/forbidden'
    | '/profile'
    | '/admin/academics'
    | '/admin/enrollments'
    | '/admin/grades'
    | '/admin/reports'
    | '/admin/section-enrollments'
    | '/admin/users'
    | '/app/grades'
    | '/app/section-enrollments'
    | '/admin/'
    | '/app/'
    | '/admin/grades/$sectionId'
    | '/admin/grades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/choose-area'
    | '/forbidden'
    | '/profile'
    | '/'
    | '/admin/academics'
    | '/admin/enrollments'
    | '/admin/reports'
    | '/admin/section-enrollments'
    | '/admin/users'
    | '/app/grades'
    | '/app/section-enrollments'
    | '/admin'
    | '/app'
    | '/admin/grades/$sectionId'
    | '/admin/grades'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/choose-area'
    | '/_authenticated/forbidden'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/_authenticated/admin/academics'
    | '/_authenticated/admin/enrollments'
    | '/_authenticated/admin/grades'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/section-enrollments'
    | '/_authenticated/admin/users'
    | '/_authenticated/app/grades'
    | '/_authenticated/app/section-enrollments'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/admin/grades/$sectionId'
    | '/_authenticated/admin/grades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forbidden': {
      id: '/_authenticated/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof AuthenticatedForbiddenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/choose-area': {
      id: '/_authenticated/choose-area'
      path: '/choose-area'
      fullPath: '/choose-area'
      preLoaderRoute: typeof AuthenticatedChooseAreaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/app/section-enrollments': {
      id: '/_authenticated/app/section-enrollments'
      path: '/section-enrollments'
      fullPath: '/app/section-enrollments'
      preLoaderRoute: typeof AuthenticatedAppSectionEnrollmentsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/grades': {
      id: '/_authenticated/app/grades'
      path: '/grades'
      fullPath: '/app/grades'
      preLoaderRoute: typeof AuthenticatedAppGradesRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/section-enrollments': {
      id: '/_authenticated/admin/section-enrollments'
      path: '/section-enrollments'
      fullPath: '/admin/section-enrollments'
      preLoaderRoute: typeof AuthenticatedAdminSectionEnrollmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/grades': {
      id: '/_authenticated/admin/grades'
      path: '/grades'
      fullPath: '/admin/grades'
      preLoaderRoute: typeof AuthenticatedAdminGradesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/enrollments': {
      id: '/_authenticated/admin/enrollments'
      path: '/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AuthenticatedAdminEnrollmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/academics': {
      id: '/_authenticated/admin/academics'
      path: '/academics'
      fullPath: '/admin/academics'
      preLoaderRoute: typeof AuthenticatedAdminAcademicsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/grades/': {
      id: '/_authenticated/admin/grades/'
      path: '/'
      fullPath: '/admin/grades/'
      preLoaderRoute: typeof AuthenticatedAdminGradesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminGradesRoute
    }
    '/_authenticated/admin/grades/$sectionId': {
      id: '/_authenticated/admin/grades/$sectionId'
      path: '/$sectionId'
      fullPath: '/admin/grades/$sectionId'
      preLoaderRoute: typeof AuthenticatedAdminGradesSectionIdRouteImport
      parentRoute: typeof AuthenticatedAdminGradesRoute
    }
  }
}

interface AuthenticatedAdminGradesRouteChildren {
  AuthenticatedAdminGradesSectionIdRoute: typeof AuthenticatedAdminGradesSectionIdRoute
  AuthenticatedAdminGradesIndexRoute: typeof AuthenticatedAdminGradesIndexRoute
}

const AuthenticatedAdminGradesRouteChildren: AuthenticatedAdminGradesRouteChildren =
  {
    AuthenticatedAdminGradesSectionIdRoute:
      AuthenticatedAdminGradesSectionIdRoute,
    AuthenticatedAdminGradesIndexRoute: AuthenticatedAdminGradesIndexRoute,
  }

const AuthenticatedAdminGradesRouteWithChildren =
  AuthenticatedAdminGradesRoute._addFileChildren(
    AuthenticatedAdminGradesRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAcademicsRoute: typeof AuthenticatedAdminAcademicsRoute
  AuthenticatedAdminEnrollmentsRoute: typeof AuthenticatedAdminEnrollmentsRoute
  AuthenticatedAdminGradesRoute: typeof AuthenticatedAdminGradesRouteWithChildren
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSectionEnrollmentsRoute: typeof AuthenticatedAdminSectionEnrollmentsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAcademicsRoute: AuthenticatedAdminAcademicsRoute,
    AuthenticatedAdminEnrollmentsRoute: AuthenticatedAdminEnrollmentsRoute,
    AuthenticatedAdminGradesRoute: AuthenticatedAdminGradesRouteWithChildren,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminSectionEnrollmentsRoute:
      AuthenticatedAdminSectionEnrollmentsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppGradesRoute: typeof AuthenticatedAppGradesRoute
  AuthenticatedAppSectionEnrollmentsRoute: typeof AuthenticatedAppSectionEnrollmentsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppGradesRoute: AuthenticatedAppGradesRoute,
  AuthenticatedAppSectionEnrollmentsRoute:
    AuthenticatedAppSectionEnrollmentsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
  AuthenticatedChooseAreaRoute: typeof AuthenticatedChooseAreaRoute
  AuthenticatedForbiddenRoute: typeof AuthenticatedForbiddenRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedChooseAreaRoute: AuthenticatedChooseAreaRoute,
  AuthenticatedForbiddenRoute: AuthenticatedForbiddenRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
