apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: academico-dev

resources:
  - namespace.yaml
  - ../../base

secretGenerator:
  - name: app-secrets
    envs:
      - .env.dev

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: patch-cookie-secure.yaml
