// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package section_enrollmentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSeats = `-- name: CountActiveSeats :one
SELECT count(*)
FROM section_enrollments
WHERE section_id = $1
  AND status <> 'withdrawn'
  AND deleted_at IS NULL
`

// Non-locking snapshot count of active inscriptions for pre-check fast-fail.
// Uses the partial index section_enrollments_active_seat_idx.
// NOT authoritative — the under-lock count is the source of truth.
func (q *Queries) CountActiveSeats(ctx context.Context, sectionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSeats, sectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const courseInProgram = `-- name: CourseInProgram :one
SELECT EXISTS(
    SELECT 1 FROM program_courses
    WHERE program_id = $1 AND course_id = $2
) AS exists
`

type CourseInProgramParams struct {
	ProgramID pgtype.UUID
	CourseID  pgtype.UUID
}

// Checks whether a course belongs to a program's course list.
// Returns a boolean; false (no row) means the course is not in the program.
func (q *Queries) CourseInProgram(ctx context.Context, arg CourseInProgramParams) (bool, error) {
	row := q.db.QueryRow(ctx, courseInProgram, arg.ProgramID, arg.CourseID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getSectionEnrollmentByID = `-- name: GetSectionEnrollmentByID :one
SELECT id, enrollment_id, section_id, status, registered_at, created_at, updated_at, deleted_at FROM section_enrollments
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSectionEnrollmentByID(ctx context.Context, id pgtype.UUID) (SectionEnrollment, error) {
	row := q.db.QueryRow(ctx, getSectionEnrollmentByID, id)
	var i SectionEnrollment
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.SectionID,
		&i.Status,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSectionEnrollmentByKeyForUpdate = `-- name: GetSectionEnrollmentByKeyForUpdate :one
SELECT id, enrollment_id, section_id, status, registered_at, created_at, updated_at, deleted_at FROM section_enrollments
WHERE enrollment_id = $1 AND section_id = $2
FOR UPDATE
`

type GetSectionEnrollmentByKeyForUpdateParams struct {
	EnrollmentID pgtype.UUID
	SectionID    pgtype.UUID
}

// Fetches the inscription row for (enrollment_id, section_id), including withdrawn rows,
// with a FOR UPDATE lock for revival detection. Lock order: acquired after section lock.
func (q *Queries) GetSectionEnrollmentByKeyForUpdate(ctx context.Context, arg GetSectionEnrollmentByKeyForUpdateParams) (SectionEnrollment, error) {
	row := q.db.QueryRow(ctx, getSectionEnrollmentByKeyForUpdate, arg.EnrollmentID, arg.SectionID)
	var i SectionEnrollment
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.SectionID,
		&i.Status,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSectionForUpdateWithWindow = `-- name: GetSectionForUpdateWithWindow :one

SELECT
    s.capacity,
    s.course_id,
    ap.enrollment_starts_at,
    ap.enrollment_ends_at
FROM sections s
JOIN academic_periods ap ON ap.id = s.academic_period_id
WHERE s.id = $1 AND s.deleted_at IS NULL
FOR UPDATE OF s
`

type GetSectionForUpdateWithWindowRow struct {
	Capacity           int32
	CourseID           pgtype.UUID
	EnrollmentStartsAt pgtype.Timestamptz
	EnrollmentEndsAt   pgtype.Timestamptz
}

// Cross-domain read strategy: queries here read enrollment, sections, academic_periods,
// and program_courses schema directly. Coupling is to the shared migration schema, not
// to Go service layers. The single transaction boundary is what makes paid+program+seat
// checks atomic. This is the canonical approach for this codebase.
// Locks the section row and fetches window columns from the joined academic period.
// Used as lock step #1 in EnrollSectionTx; lock order is section → key row.
func (q *Queries) GetSectionForUpdateWithWindow(ctx context.Context, id pgtype.UUID) (GetSectionForUpdateWithWindowRow, error) {
	row := q.db.QueryRow(ctx, getSectionForUpdateWithWindow, id)
	var i GetSectionForUpdateWithWindowRow
	err := row.Scan(
		&i.Capacity,
		&i.CourseID,
		&i.EnrollmentStartsAt,
		&i.EnrollmentEndsAt,
	)
	return i, err
}

const insertSectionEnrollment = `-- name: InsertSectionEnrollment :one
INSERT INTO section_enrollments (enrollment_id, section_id, status)
VALUES ($1, $2, 'in_progress')
RETURNING id, enrollment_id, section_id, status, registered_at, created_at, updated_at, deleted_at
`

type InsertSectionEnrollmentParams struct {
	EnrollmentID pgtype.UUID
	SectionID    pgtype.UUID
}

func (q *Queries) InsertSectionEnrollment(ctx context.Context, arg InsertSectionEnrollmentParams) (SectionEnrollment, error) {
	row := q.db.QueryRow(ctx, insertSectionEnrollment, arg.EnrollmentID, arg.SectionID)
	var i SectionEnrollment
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.SectionID,
		&i.Status,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listOwnSectionEnrollments = `-- name: ListOwnSectionEnrollments :many
SELECT se.id, se.enrollment_id, se.section_id, se.status, se.registered_at, se.created_at, se.updated_at, se.deleted_at
FROM section_enrollments se
JOIN enrollments e ON e.id = se.enrollment_id
WHERE e.student_id = $1
  AND se.deleted_at IS NULL
ORDER BY se.created_at
`

// Returns all live inscriptions for a student by joining enrollments on student_id.
func (q *Queries) ListOwnSectionEnrollments(ctx context.Context, studentID pgtype.UUID) ([]SectionEnrollment, error) {
	rows, err := q.db.Query(ctx, listOwnSectionEnrollments, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SectionEnrollment
	for rows.Next() {
		var i SectionEnrollment
		if err := rows.Scan(
			&i.ID,
			&i.EnrollmentID,
			&i.SectionID,
			&i.Status,
			&i.RegisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionEnrollments = `-- name: ListSectionEnrollments :many
SELECT id, enrollment_id, section_id, status, registered_at, created_at, updated_at, deleted_at FROM section_enrollments
WHERE deleted_at IS NULL
  AND ($1::uuid IS NULL   OR section_id   = $1::uuid)
  AND ($2::uuid IS NULL OR enrollment_id = $2::uuid)
  AND ($3::text IS NULL        OR status        = $3::text)
ORDER BY created_at
`

type ListSectionEnrollmentsParams struct {
	SectionID    pgtype.UUID
	EnrollmentID pgtype.UUID
	Status       pgtype.Text
}

func (q *Queries) ListSectionEnrollments(ctx context.Context, arg ListSectionEnrollmentsParams) ([]SectionEnrollment, error) {
	rows, err := q.db.Query(ctx, listSectionEnrollments, arg.SectionID, arg.EnrollmentID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SectionEnrollment
	for rows.Next() {
		var i SectionEnrollment
		if err := rows.Scan(
			&i.ID,
			&i.EnrollmentID,
			&i.SectionID,
			&i.Status,
			&i.RegisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolvePaidEnrollmentByID = `-- name: ResolvePaidEnrollmentByID :one
SELECT e.id, e.student_id, e.program_id, e.status
FROM enrollments e
WHERE e.id = $1
  AND e.status = 'paid'
  AND e.deleted_at IS NULL
`

type ResolvePaidEnrollmentByIDRow struct {
	ID        pgtype.UUID
	StudentID pgtype.UUID
	ProgramID pgtype.UUID
	Status    string
}

// Fetches an enrollment by id and verifies it is paid (used in admin path).
func (q *Queries) ResolvePaidEnrollmentByID(ctx context.Context, id pgtype.UUID) (ResolvePaidEnrollmentByIDRow, error) {
	row := q.db.QueryRow(ctx, resolvePaidEnrollmentByID, id)
	var i ResolvePaidEnrollmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ProgramID,
		&i.Status,
	)
	return i, err
}

const resolvePaidEnrollmentForProgram = `-- name: ResolvePaidEnrollmentForProgram :one
SELECT e.id, e.student_id, e.program_id, e.status
FROM enrollments e
WHERE e.student_id = $1
  AND e.program_id = $2
  AND e.status = 'paid'
  AND e.deleted_at IS NULL
LIMIT 1
`

type ResolvePaidEnrollmentForProgramParams struct {
	StudentID pgtype.UUID
	ProgramID pgtype.UUID
}

type ResolvePaidEnrollmentForProgramRow struct {
	ID        pgtype.UUID
	StudentID pgtype.UUID
	ProgramID pgtype.UUID
	Status    string
}

// Resolves the paid enrollment for a student in a given program.
// Returns ErrNoRows when no paid enrollment exists (pending/cancelled/missing).
func (q *Queries) ResolvePaidEnrollmentForProgram(ctx context.Context, arg ResolvePaidEnrollmentForProgramParams) (ResolvePaidEnrollmentForProgramRow, error) {
	row := q.db.QueryRow(ctx, resolvePaidEnrollmentForProgram, arg.StudentID, arg.ProgramID)
	var i ResolvePaidEnrollmentForProgramRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ProgramID,
		&i.Status,
	)
	return i, err
}

const resolvePaidEnrollmentForStudentAndCourse = `-- name: ResolvePaidEnrollmentForStudentAndCourse :one
SELECT e.id, e.student_id, e.program_id, e.status
FROM enrollments e
JOIN program_courses pc ON pc.program_id = e.program_id
WHERE e.student_id = $1
  AND pc.course_id = $2
  AND e.status = 'paid'
  AND e.deleted_at IS NULL
LIMIT 1
`

type ResolvePaidEnrollmentForStudentAndCourseParams struct {
	StudentID pgtype.UUID
	CourseID  pgtype.UUID
}

type ResolvePaidEnrollmentForStudentAndCourseRow struct {
	ID        pgtype.UUID
	StudentID pgtype.UUID
	ProgramID pgtype.UUID
	Status    string
}

// Resolves the paid enrollment for a student whose enrolled program contains the given
// course. Used by the student self-service path when no enrollment_id is provided in
// the request: the program is inferred from the section's course_id.
func (q *Queries) ResolvePaidEnrollmentForStudentAndCourse(ctx context.Context, arg ResolvePaidEnrollmentForStudentAndCourseParams) (ResolvePaidEnrollmentForStudentAndCourseRow, error) {
	row := q.db.QueryRow(ctx, resolvePaidEnrollmentForStudentAndCourse, arg.StudentID, arg.CourseID)
	var i ResolvePaidEnrollmentForStudentAndCourseRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ProgramID,
		&i.Status,
	)
	return i, err
}

const reviveSectionEnrollment = `-- name: ReviveSectionEnrollment :one
UPDATE section_enrollments
SET status     = 'in_progress',
    deleted_at = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, enrollment_id, section_id, status, registered_at, created_at, updated_at, deleted_at
`

// Revives a withdrawn inscription: sets status back to in_progress and clears deleted_at.
func (q *Queries) ReviveSectionEnrollment(ctx context.Context, id pgtype.UUID) (SectionEnrollment, error) {
	row := q.db.QueryRow(ctx, reviveSectionEnrollment, id)
	var i SectionEnrollment
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.SectionID,
		&i.Status,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const withdrawSectionEnrollment = `-- name: WithdrawSectionEnrollment :one
UPDATE section_enrollments
SET status     = 'withdrawn',
    updated_at = now()
WHERE id = $1 AND status = 'in_progress' AND deleted_at IS NULL
RETURNING id, enrollment_id, section_id, status, registered_at, created_at, updated_at, deleted_at
`

// Transitions an in_progress inscription to withdrawn.
// Sets updated_at; does NOT set deleted_at — withdrawn rows are retained for audit/revival.
func (q *Queries) WithdrawSectionEnrollment(ctx context.Context, id pgtype.UUID) (SectionEnrollment, error) {
	row := q.db.QueryRow(ctx, withdrawSectionEnrollment, id)
	var i SectionEnrollment
	err := row.Scan(
		&i.ID,
		&i.EnrollmentID,
		&i.SectionID,
		&i.Status,
		&i.RegisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
