// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package section_enrollmentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Non-locking snapshot count of active inscriptions for pre-check fast-fail.
	// Uses the partial index section_enrollments_active_seat_idx.
	// NOT authoritative — the under-lock count is the source of truth.
	CountActiveSeats(ctx context.Context, sectionID pgtype.UUID) (int64, error)
	// Checks whether a course belongs to a program's course list.
	// Returns a boolean; false (no row) means the course is not in the program.
	CourseInProgram(ctx context.Context, arg CourseInProgramParams) (bool, error)
	GetSectionEnrollmentByID(ctx context.Context, id pgtype.UUID) (SectionEnrollment, error)
	// Fetches the inscription row for (enrollment_id, section_id), including withdrawn rows,
	// with a FOR UPDATE lock for revival detection. Lock order: acquired after section lock.
	GetSectionEnrollmentByKeyForUpdate(ctx context.Context, arg GetSectionEnrollmentByKeyForUpdateParams) (SectionEnrollment, error)
	// Cross-domain read strategy: queries here read enrollment, sections, academic_periods,
	// and program_courses schema directly. Coupling is to the shared migration schema, not
	// to Go service layers. The single transaction boundary is what makes paid+program+seat
	// checks atomic. This is the canonical approach for this codebase.
	// Locks the section row and fetches window columns from the joined academic period.
	// Used as lock step #1 in EnrollSectionTx; lock order is section → key row.
	GetSectionForUpdateWithWindow(ctx context.Context, id pgtype.UUID) (GetSectionForUpdateWithWindowRow, error)
	InsertSectionEnrollment(ctx context.Context, arg InsertSectionEnrollmentParams) (SectionEnrollment, error)
	// Returns all live inscriptions for a student by joining enrollments on student_id.
	ListOwnSectionEnrollments(ctx context.Context, studentID pgtype.UUID) ([]SectionEnrollment, error)
	ListSectionEnrollments(ctx context.Context, arg ListSectionEnrollmentsParams) ([]SectionEnrollment, error)
	// Fetches an enrollment by id and verifies it is paid (used in admin path).
	ResolvePaidEnrollmentByID(ctx context.Context, id pgtype.UUID) (ResolvePaidEnrollmentByIDRow, error)
	// Resolves the paid enrollment for a student in a given program.
	// Returns ErrNoRows when no paid enrollment exists (pending/cancelled/missing).
	ResolvePaidEnrollmentForProgram(ctx context.Context, arg ResolvePaidEnrollmentForProgramParams) (ResolvePaidEnrollmentForProgramRow, error)
	// Resolves the paid enrollment for a student whose enrolled program contains the given
	// course. Used by the student self-service path when no enrollment_id is provided in
	// the request: the program is inferred from the section's course_id.
	ResolvePaidEnrollmentForStudentAndCourse(ctx context.Context, arg ResolvePaidEnrollmentForStudentAndCourseParams) (ResolvePaidEnrollmentForStudentAndCourseRow, error)
	// Revives a withdrawn inscription: sets status back to in_progress and clears deleted_at.
	ReviveSectionEnrollment(ctx context.Context, id pgtype.UUID) (SectionEnrollment, error)
	// Transitions an in_progress inscription to withdrawn.
	// Sets updated_at; does NOT set deleted_at — withdrawn rows are retained for audit/revival.
	WithdrawSectionEnrollment(ctx context.Context, id pgtype.UUID) (SectionEnrollment, error)
}

var _ Querier = (*Queries)(nil)
